### ISSUE TITLE
(Possible) Useless Entries (a-c)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#10]
Following entries returned 301 code to automated queries. Manual verification performed to see what is behind. 

page not found:
a2put.chinaz.com

for sale:
audit8.com

404:
cdxyb.cn
chinaairs.cn
chuangyixi.com
cqgya.com

**Comment by cjx82630** [comment]
https://a2put.chinaz.com/propagate.js
Registrar Registration Expiration Date: 2026-12-19T21:41:44Z
\ audit8.com
   Registry Expiry Date: 2021-11-18T19:17:28Z

Registrar Registration Expiration Date: 2021-11-18T19:17:28Z
\ cdxyb.cn
Expiration Time: 2021-05-20 06:55:12
\ chinaairs.cn
Expiration Time: 2021-12-31 09:59:26
\ chuangyixi.com
   Registry Expiry Date: 2021-04-06T13:21:02Z

\ cqgya.com
   Registry Expiry Date: 2021-09-12T04:57:53Z
