### ISSUE TITLE
百度文库搜索广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#101]
链接：https://wenku.baidu.com/search?word=%E6%A1%A5%E7%89%8C%E6%97%A0%E5%B0%86%E6%80%8E%E4%B9%88%E6%89%93

截图：
![](https://user-images.githubusercontent.com/81752398/146728957-73fd25ec-29c9-49a0-9006-1ae94daa38f9.png)

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
