### ISSUE TITLE
疑似无效规则

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#112]
https://github.com/easylist/easylistchina/commit/e5619794262113b1cd16284d069ebf2bbdd050b7#diff-bdf5dc9e0146dcf4d7951836441a936deb4fa8445e48dba82c991fb85567696e
```
gamersky.com#@#.like2
```
该规则似乎无效，请检查一下，谢谢！

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
