### ISSUE TITLE
无效规则

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#113]
https://github.com/easylist/easylistchina/commit/c3e1427dc87ef7209c6190d50a45f40a6018a961#diff-bdf5dc9e0146dcf4d7951836441a936deb4fa8445e48dba82c991fb85567696e
```
bilibili.com#@#.follow-wrapper
```
`Fanboy’s Social`列表中没有隐藏这个元素，没有这个过滤器
```
##.follow-wrapper
```

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
