### ISSUE TITLE
头条巨量引擎追踪器

### ISSUE THREAD

**Issue by xymopen** [easylist/easylistchina#114]
这个应该放在 EasyPrivacy 里还是这里？

https://event-manager.oceanengine.com/docs/8650/jssdk_docs/#%E5%AE%8C%E6%88%90js%E5%9F%8B%E7%A0%81

https://analytics.oceanengine.com/api/v2/js/sdk

**Comment by cjx82630** [comment]
反馈到 https://github.com/easylist/easylist/issues

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/80ffe32b7dc2390313e37f6cc12246588fe0b74b
