### ISSUE TITLE
重复规则

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#116]
https://github.com/easylist/easylistchina/blob/18d04c0432dce777d3f6ef2a75528f234e34bf6a/easylistchina.txt#L20955
请删除这一重复规则，因为已经添加到了Fanboy规则中，谢谢
见 – https://github.com/easylist/easylist/blob/8cf83867b4ceca9639e2121e581dfbdd160e3306/fanboy-addon/fanboy_social_allowlist_general_hide.txt#L36

**Comment by cjx82630** [comment]
Done.
