### ISSUE TITLE
无效规则

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#117]
https://github.com/easylist/easylistchina/blob/18d04c0432dce777d3f6ef2a75528f234e34bf6a/easylistchina.txt#L20977
这个过滤器已经被添加到了Fanboy列表中，请移除，谢谢
https://github.com/easylist/easylist/blob/f026aa3c0e15cf319c8d8db78b27a91cb003b7a0/fanboy-addon/fanboy_social_allowlist_general_hide.txt#L283

**Comment by cjx82630** [comment]
Fixed.
