### ISSUE TITLE
百度知道部分商业账号自带广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#119]
链接：https://zhidao.baidu.com/question/1375422522812283139

截图：![image](https://user-images.githubusercontent.com/81752398/147875451-a7509ee4-5f7d-4f8b-9d6b-d689208be4ac.png)

这个号每个回答都带了广告

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.

**Comment by MkQtS** [comment]
@cjx82630 移动端广告依然存在

![image](https://user-images.githubusercontent.com/81752398/147876920-27c0ebe6-d198-431b-a695-288cf4efe1e1.png)

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
