### ISSUE TITLE
(Possible) Useless Entries (g-i)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#12]
Following entries returned a 301 code to automated query. Manual verification performed to see what's behind. 

404:
grjs02.com
grjs06.com
hz-sllace.com
itchenjian.com

Empty response:
hbhtbn.com

IP address cannot be found:
hbyingchang.cn
hfjuki.com

Unregistered at MIIT:
ihhii.xyz

**Comment by cjx82630** [comment]
\ grjs02.com
   Registry Expiry Date: 2021-10-04T14:48:48Z

Registrar Registration Expiration Date: 2021-10-04T07:00:00Z
\ grjs06.com
   Registry Expiry Date: 2021-10-04T14:48:48Z

Registrar Registration Expiration Date: 2021-10-04T07:00:00Z
\ hz-sllace.com
   Registry Expiry Date: 2021-08-25T18:01:13Z

Registrar Registration Expiration Date: 2021-08-26T02:01:13Z

\ itchenjian.com
   Registry Expiry Date: 2021-09-28T02:35:50Z

\ hbhtbn.com
   Registry Expiry Date: 2022-01-10T19:30:56Z

Registrar Registration Expiration Date: 2022-01-11T03:30:56Z

\ hbyingchang.cn
Expiration Time: 2021-10-10 14:58:25
\ hfjuki.com
   Registry Expiry Date: 2021-06-27T11:00:19Z

Registrar Registration Expiration Date: 2021-06-27T07:00:00Z
\ ihhii.xyz
Registry Expiry Date: 2021-05-29T23:59:59.0Z
