### ISSUE TITLE
(Possible) Useless Entries (j-l)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#13]
Following entries returned a 301 code to automated query. Manual verification performed to see what's behind.

404:
jianxinshanghai.com
just-machinery.com

Redirect to search engine:
lady177.com
ladsblue.com

**Comment by cjx82630** [comment]
\ jianxinshanghai.com
   Registry Expiry Date: 2021-11-23T19:26:35Z

\ just-machinery.com
   Registry Expiry Date: 2021-09-23T18:26:28Z

\ lady177.com
   Registry Expiry Date: 2021-10-27T18:55:49Z

Registrar Registration Expiration Date: 2021-10-28T02:55:49Z

\ ladsblue.com
   Registry Expiry Date: 2021-06-17T11:26:51Z
