### ISSUE TITLE
重复规则

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#131]
https://github.com/easylist/easylistchina/blob/8821ff3a8f41812c66335008489e8bd5aa49415f/easylistchina.txt#L21557
已经添加到`Fanboy’s Annoyance`中，见：https://github.com/easylist/easylist/blob/b38423bc7dceba1c9be433029ddc147214583a82/fanboy-addon/fanboy_social_allowlist_general_hide.txt#L223
谢谢！

**Comment by cjx82630** [comment]
9e3fd62dff0ac380d3722a91b2bfca85487d3943
