### ISSUE TITLE
A: http://m.szjjzs.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#132]
Top banner gifs at http://m.szjjzs.com/

```
||wfsyjq.com
||leku99.cc
```
<img width="820" alt="Screenshot 2022-02-04 at 15 41 49" src="https://user-images.githubusercontent.com/65717387/152548026-17b6d917-0c67-43aa-b100-384cdbadcb67.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
