### ISSUE TITLE
果核剥壳广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#134]
链接：https://www.ghxi.com/snipaste.html

截图：![2022_0205_1937_48](https://user-images.githubusercontent.com/81752398/152640519-bbb47d63-ae1e-4d46-8ad1-a9c1dbd7fbe4.png)

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.

**Comment by MkQtS** [comment]
@cjx82630 此网站似乎做了针对性的更新，`ghxi.com##.ad_single_1`已经失效了

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
