### ISSUE TITLE
可疑规则

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#135]
`||qinqiaotrade.com`, `||itv.hexun.com`这两条规则末尾应该少了个`^`

这条规则`$image,domain=ip.cn`似乎过于严格，而且ip.cn只尝试加载了`https://www.ip.cn/img/favicon.ico`一个image

**Comment by cjx82630** [comment]
移除过时规则.30分钟后更新.
Fixed.Please manually update in 30 minutes.

**Comment by MkQtS** [comment]
@cjx82630，`||itv.hexun.com`还没有处理，需要处理吗？

**Comment by cjx82630** [comment]
这可以覆盖hexun.com.tw, hexun.com.cn, 即使这些域名可能不再启用.
