### ISSUE TITLE
https://www.freedidi.com/4166.html

### ISSUE THREAD

**Issue by foxdodo** [easylist/easylistchina#136]
进入网站https://www.freedidi.com 点击任何一个网页都会提示关闭adblock, 并遮挡网页内容

使用环境:
edge浏览器 UBO
默认规则+
CHN: AdGuard Chinese (中文) 2,132 / 27,895
乘风 广告过滤规则 1,143 / 1,167

CJX's Annoyance List 1,896 / 1,899

CJX's EasyList Lite 497 / 516

EasyList China 25,704 / 25,720

NoCoin Filter List

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.

**Comment by foxdodo** [comment]
更新了不管用, 排除了一遍发现是乘风的规则触发了检测😂
