### ISSUE TITLE
https://www.haiyuer.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#138]
**Tested as Mobile**

Block banners at https://www.haiyuer.com/

Screenshots: 
<img width="864" alt="Screenshot 2022-02-10 at 10 06 23" src="https://user-images.githubusercontent.com/65717387/153374001-d6d6befe-3f29-4fe3-9e68-91270dddd5e7.png">
<img width="1100" alt="Screenshot 2022-02-10 at 10 07 10" src="https://user-images.githubusercontent.com/65717387/153374108-a825a87c-e75a-48e5-884f-3f07fd1b7cb5.png">

Filter ideas: 
`||jsdelivr.net/gh/kximg/apppic/*.gif`
`||haiyuer.com/uc.js`

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
