### ISSUE TITLE
A: http://23.225.40.82/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#139]
Block adservers at http://23.225.40.82/

Possible Filter: `||ke2kzw.com^`

Screenshot:
<img width="1436" alt="Screenshot 2022-02-11 at 09 50 27" src="https://user-images.githubusercontent.com/65717387/153562078-6e82553d-8058-489d-b1f4-30e04590e1f8.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
