### ISSUE TITLE
(Possible) Useless Entries (m-o)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#14]
Following entries returned a 301 code to automated query. Manual verification performed to see what's behind.

404:
meethanshi.com
ni87.com
njmpacc.com
oceanbot-steam.com

Redirect to search engine:
myselfjanitor.com
newjulads.com
newsatads.com

**Comment by cjx82630** [comment]
\ meethanshi.com
   Registry Expiry Date: 2021-10-20T18:00:48Z

\ ni87.com
   Registry Expiry Date: 2021-08-06T18:09:54Z

Registrar Registration Expiration Date: 2021-08-06T18:09:54Z
\ njmpacc.com
   Registry Expiry Date: 2021-06-28T18:09:10Z

Registrar Registration Expiration Date: 2021-06-29T02:09:10Z

\ oceanbot-steam.com
   Registry Expiry Date: 2021-09-26T18:20:10Z

\ myselfjanitor.com
   Registry Expiry Date: 2021-07-23T02:35:15Z

Registrar Registration Expiration Date: 2021-07-23T02:35:00.00Z

Registrar Registration Expiration Date: 2021-07-23T02:35:00.00Z

\ newjulads.com
   Registry Expiry Date: 2022-03-05T10:47:18Z

Registrar Registration Expiration Date: 2021-03-05T10:47:18.00Z

Registrar Registration Expiration Date: 2021-03-05T10:47:18.00Z

\ newsatads.com
   Registry Expiry Date: 2022-03-05T10:46:30Z
