### ISSUE TITLE
https://m.yushubo.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#142]
Banners + redirects at https://m.yushubo.com/read_39272_5089.html

Screenshot: 
<img width="978" alt="Screenshot 2022-02-21 at 10 41 05" src="https://user-images.githubusercontent.com/65717387/154928823-50899a43-94d7-44a2-b610-32b86381fd14.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
