### ISSUE TITLE
https://www.tptoon.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#145]
Banners at https://www.tptoon.com/

Screenshot: 
<img width="1206" alt="Screenshot 2022-02-28 at 11 48 54" src="https://user-images.githubusercontent.com/65717387/155970572-4df2b228-e17e-470d-8b07-a775929ef3c2.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
