### ISSUE TITLE
1090ys2已经更换了1090ys8

### ISSUE THREAD

**Issue by jasonandy999** [easylist/easylistchina#147]
**已经更换了网址，请更新一下！以及介绍页面有弹窗http://1090ys8.com/show/80317.html**

![QQ图片20220304022528](https://user-images.githubusercontent.com/59506376/156628839-210176c6-a7c5-40d2-be53-98a4b67ed215.png)

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
