### ISSUE TITLE
1090ys8广告还是有弹窗，tvyb10.com有跳转

### ISSUE THREAD

**Issue by jasonandy999** [easylist/easylistchina#148]
http://1090ys8.com/
![QQ图片20220305192120](https://user-images.githubusercontent.com/59506376/156880983-e50ab9f0-ea89-4540-ae5c-294cb61fbde8.png)

首页有弹窗广告，希望能遮蔽

http://www.tvyb10.com/vod/play/id/179851/sid/3/nid/1.html
![QQ图片20220305192843](https://user-images.githubusercontent.com/59506376/156881136-8b01cc3f-68a5-4c21-9c63-fca3fb0b704a.png)

有严重弹窗跳转，尤其是是播放页面，然而几个域名都是一样的：
这几个域名同一个模板：tvyb10.com、tvyb02.com、hktv02.com、hktv03.com

这几个域名又同一个网站模板：tvyb01.com与tvyb03.com

**Comment by cjx82630** [comment]
官方列表不过滤公告,APP下载
