### ISSUE TITLE
(Possible) Useless Entries (s-u)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#16]
Following entries returned a 301 code to automated query. Manual verification performed to see what's behind.

404:
shukongshebei.net
tjhhr.com

Redirect to pptv:
synacast.com

Redirect to search engine:
shackapple.com

**Comment by cjx82630** [comment]
\ shukongshebei.net
   Registry Expiry Date: 2021-11-01T04:11:34Z

Registrar Registration Expiration Date: 2021-11-01T04:11:34Z

\ tjhhr.com
   Registry Expiry Date: 2021-05-27T00:40:55Z

\ synacast.com
   Registry Expiry Date: 2022-06-15T07:00:52Z

Registrar Registration Expiration Date: 2022-06-14T16:00:00Z
\ shackapple.com
   Registry Expiry Date: 2021-08-07T02:05:54Z
