### ISSUE TITLE
https://yemancomic.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#166]
**Mobile**

Gif banner at https://yemancomic.com/

Screenshot:
<img width="918" alt="Screenshot 2022-03-28 at 06 51 12" src="https://user-images.githubusercontent.com/65717387/160328814-91006167-b897-4a87-a75d-22d2d54bc2c9.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
