### ISSUE TITLE
https://m.duhama.tv/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#167]
footer gif banner at https://m.duhama.tv/

**Mobile**

<img width="1294" alt="Screenshot 2022-03-28 at 10 25 34" src="https://user-images.githubusercontent.com/65717387/160357479-7cebb6d2-463d-4dc1-bcf0-3a53b558f0ab.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
