### ISSUE TITLE
https://m.dmhuah.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#169]
Inside banners at https://m.dmhuah.com/manhua/huanghouhenmang/1807948.html

**Mobile**

Screenshots: 

<img width="1176" alt="Screenshot 2022-03-29 at 11 11 05" src="https://user-images.githubusercontent.com/65717387/160577232-aa51a4fe-9617-4f4c-879a-e89696c97292.png">
<img width="614" alt="Screenshot 2022-03-29 at 11 09 00" src="https://user-images.githubusercontent.com/65717387/160577241-94e931f4-2f11-43d1-ad52-50997e83abfa.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
