### ISSUE TITLE
(Possible) Useless Entries (v-x)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#17]
Following entries returned a 301 code to automated query. Manual verification performed to see what's behind.

404:
weifengtianxia.com
wzsygdl.com

502
weimeicar.cn

**Comment by cjx82630** [comment]
\ weifengtianxia.com
   Registry Expiry Date: 2021-11-26T19:14:27Z

Registrar Registration Expiration Date: 2021-11-26T00:00:00.000Z

\ wzsygdl.com
   Registry Expiry Date: 2021-03-20T06:54:10Z

Registrar Registration Expiration Date: 2021-03-20T01:54:10Z

\ weimeicar.cn
Expiration Time: 2021-05-31 14:21:53
