### ISSUE TITLE
https://www.kkkshu.co/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#173]
Bottom banners at https://www.kkkshu.co/
**mobile**

Screenshot: 
<img width="1020" alt="Screenshot 2022-04-05 at 10 42 19" src="https://user-images.githubusercontent.com/65717387/161714608-06d81ff6-9b1a-4f54-b2ce-656ba12ffb7b.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
