### ISSUE TITLE
http://www.mangabz.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#174]
Gif banners **Mobile**
http://www.mangabz.com/m220463/

<img width="503" alt="Screenshot 2022-04-07 at 09 24 53" src="https://user-images.githubusercontent.com/65717387/162143436-9e7a12ad-8306-4c40-b9ab-af217443d700.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
