### ISSUE TITLE
[NSFW] https://boye.xyz/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#176]
Banners + Redirects at https://boye.xyz/

**Mobile**

Screenshot: 
<img width="617" alt="Screenshot 2022-04-08 at 09 04 17" src="https://user-images.githubusercontent.com/65717387/162382331-7513c7d6-6842-4b9a-a43c-0025914647f1.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
