### ISSUE TITLE
https://m.dmhuah.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#178]
Gif banners (footer) at https://m.dmhuah.com/

**mobile**
<img width="1067" alt="Screenshot 2022-04-08 at 09 41 46" src="https://user-images.githubusercontent.com/65717387/162389083-9122a308-8509-4fd1-886d-41d00c3a628a.png">

**Comment by cjx82630** [comment]
早些时候已处理.请手动更新.
Fixed sometime ago.Please manually update now.

**Comment by felippesantos46** [comment]
> 早些时候已处理.请手动更新. Fixed sometime ago.Please manually update now.

Thank you, my bad 😅
