### ISSUE TITLE
(Possible) Useless Entries (y,z)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#18]
Following entries returned a 301 code to automated query. Manual verification performed to see what's behind.

404:

zcrtd.com

Empty response:

ysjweb.com
yzjlsb.com
zoujuhonglawyer.com
zzqqhb.com

for sale:
zymro.com

Redirect to aliyun:
youfumei.com

Time permitted, I will also check whether the domains on which the element blocking, hiding and altering rules are based are still active.

**Comment by cjx82630** [comment]
\ zcrtd.com
   Registry Expiry Date: 2021-10-19T01:14:58Z

Registrar Registration Expiration Date: 2021-10-19T01:14:58Z
\ ysjweb.com
   Registry Expiry Date: 2021-04-06T18:28:49Z

Registrar Registration Expiration Date: 2021-04-06T00:00:00.000Z

\ yzjlsb.com
   Registry Expiry Date: 2021-09-26T00:56:07Z

Registrar Registration Expiration Date: 2021-09-26T00:56:07Z

\ zoujuhonglawyer.com
   Registry Expiry Date: 2021-11-07T04:11:14Z

\ zzqqhb.com
   Registry Expiry Date: 2021-06-01T04:43:03Z

\ zymro.com
   Registry Expiry Date: 2021-05-29T19:13:31Z

Registrar Registration Expiration Date: 2021-05-29T19:13:31.0Z
\ youfumei.com
   Registry Expiry Date: 2021-07-13T18:45:24Z
