### ISSUE TITLE
Gif banners

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#181]
Top gif banners at [NSFW] https://m.waimanwu.com/ + http://m.soduha.com/

**Mobile**

Screenshots: 
<img width="614" alt="Screenshot 2022-04-11 at 10 53 31" src="https://user-images.githubusercontent.com/65717387/162701047-dce6bc16-dd65-4ffb-b1a2-75ed1a23b4f0.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
