### ISSUE TITLE
Bilibili付费课程广告

### ISSUE THREAD

**Issue by TigerCubDen** [easylist/easylistchina#183]
![image](https://user-images.githubusercontent.com/55782476/163387828-1ecb5fb8-c3c1-4506-a402-0ffaf2be14a5.png)
红框为广告，绿框为正常内容
过滤规则为：`bilibili.com##.video-page-special-card`

**Comment by cjx82630** [comment]
不过滤自我推广或正常内容.你可以点击ABP图标>拦截元素.或依 https://help.eyeo.com/en/adblockplus/how-to-write-filters 攥写规则.
