### ISSUE TITLE
hkepc.com

### ISSUE THREAD

**Issue by otksm** [easylist/easylistchina#184]
### List the website(s) you're having issues:

`https://www.hkepc.com/review`

### What happens?

`hkepc.com###headBanner`

Ad placeholders. One of the `headBanner` ads uses _div id_ instead of _div class_.

### List Subscriptions you're using:

EasyList China

### Your settings

- Browser/version: Firefox 99.0.1
- Adblock Extension/version: uBlock Origin 1.42.4

### Other details:

`hkepc.com##.headBanner` is still valid in other parts of this site.

**Comment by cjx82630** [comment]
There is no different between adding the filter or not.
