### ISSUE TITLE
A: [NSFW] http://www.pornbest.org/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#187]
Ad banners at http://www.pornbest.org/

**Mobile** 

Screenshots: 
<img width="888" alt="Screenshot 2022-04-25 at 11 24 18" src="https://user-images.githubusercontent.com/65717387/165060870-8e239ff0-60b0-4524-8f67-1367fc802907.png">

**Comment by cjx82630** [comment]
Cannot reproduce. Try ABP.

**Comment by felippesantos46** [comment]
> Cannot reproduce. Try ABP.

Hey @cjx82630 thank you fro the review! 
As i'm usually testing mobile and the app do not support ABP, i decided to open the issue in here. 
On the other hand i cannot reproduce anymore as well 😅.
