### ISSUE TITLE
https://m.ranwen.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#189]
Bottom banners at https://m.ranwen.com/

**Mobile**

<img width="972" alt="Screenshot 2022-04-28 at 13 07 54" src="https://user-images.githubusercontent.com/65717387/165739219-d1297907-503c-40bb-a69b-9a5605254aef.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
