### ISSUE TITLE
这个不是广告联盟的，请移除下，谢谢

### ISSUE THREAD

**Issue by oyjcmyn** [easylist/easylistchina#19]
https://github.com/easylist/easylistchina/blob/9b932f59dfd23079557d8f4da1c7c45cb5244a83/easylistchina.txt#L1182
这两个只是放在自己网站上的内容。www.miued.com

**Comment by cjx82630** [comment]
属于广告

**Comment by oyjcmyn** [comment]
要屏蔽上面的广告，屏蔽这个吧。gg.miued.com 
不要整个域名，要不视频无法播放了

**Comment by cjx82630** [comment]
已更新
