### ISSUE TITLE
http://ddd-smart.net/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#196]
Seems to be a banner. it redirect to: https://kpia.shop/lp/lp_s-4/index.html?from=img-2
<img width="421" alt="Screenshot 2022-05-23 at 15 18 12" src="https://user-images.githubusercontent.com/65717387/169828428-1c43afef-a609-4c60-80ca-acc85a1c5505.png">

Also popups
<img width="1121" alt="Screenshot 2022-05-23 at 15 21 24" src="https://user-images.githubusercontent.com/65717387/169828780-7f54962e-bdcb-404a-885a-cc3e6c357620.png">

**Comment by cjx82630** [comment]
1)If you want to report english websites or embed player,please email URL to easylist.subscription@gmail.com  2)If other language,please subscribe https://adblockplus.org/en/subscriptions
