### ISSUE TITLE
https://www.yikedy.co/

### ISSUE THREAD

**Issue by CbumDino** [easylist/easylistchina#197]
Banners at https://www.yikedy.co/

**Mobile**

Screenshot:
<img width="524" alt="Screenshot 2022-05-23 at 15 46 45" src="https://user-images.githubusercontent.com/65717387/169833784-d9c48616-b86e-4096-bae4-baf4ac1d5175.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
