### ISSUE TITLE
thwiki.cc的轮播是用于公告用途不是广告

### ISSUE THREAD

**Issue by Whuihuan** [easylist/easylistchina#199]
由于规则屏蔽已经影响网站的正常用途了。THB是东方project的WIKI，轮播里有引导购买正版作品也是很正常的事情。更何况里面有宣传THB其他关联项目的用途。判定为广告去屏蔽是不合适的，并且也不是投放了收益化广告，这些都是内部流量，根本无法收益化

**Comment by cjx82630** [comment]
淘宝店是否网站方的? 建议广告与内容分开放置, 便于网友分辨.

**Comment by Whuihuan** [comment]
> 淘宝店是否网站方的? 建议广告与内容分开放置, 便于网友分辨.

淘宝店是我们的，因为东方project官方中文正版出版物也是我们和出版方天闻角川合作出版的，所以才会挂着我们网店的商品内容。这些其实是得到了大多数用户的认可。

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
因有反映烦扰, 移动到 9ae062e17726d28105eec264389114631df6ac98
