### ISSUE TITLE
https://unpkg.com/

### ISSUE THREAD

**Issue by Trezedo** [easylist/easylistchina#201]
该网站提供的CDN服务被拦截，例如 css 和 js，影响网站运行。

The CDN service provided by this website is blocked, which causes websites using `unpkg` CDN to work abnormally.

**Comment by spahl** [comment]
https://github.com/easylist/easylistchina/blob/4241a32467f065ceec6a02be3e81676e9c0bda84/easylistchina.txt#L3993
