### ISSUE TITLE
[NSFW] https://www.xiurenb.com/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#204]
banners at https://www.xiurenb.com/

**Mobile**

Screenshot: 
<img width="276" alt="Screenshot 2022-06-10 at 09 32 24" src="https://user-images.githubusercontent.com/65717387/173014271-1c309e8d-02d2-42b2-9d55-b33609959364.png">

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes. 8df274b1365b63c632cd04f6fbd2f1b671d593c9
