### ISSUE TITLE
请求新增对 openwrite.cn 引流公众号功能的拦截

### ISSUE THREAD

**Issue by ljm12914** [easylist/easylistchina#208]
### 存在问题的网址：接入了 openwrite 引流公众号功能 (https:/\/openwrite.cn/guide/readmore/) 的网站。例如：
[jb51.cc](https://www.jb51.cc/)

### 什么问题？
以隐藏内容方式引流公众号应被视为具有强侵入性的广告而受到无条件屏蔽。

### 做法
添加以下拦截规则：
```
readmore.openwrite.cn/js/readmore.js
```

**Comment by cjx82630** [comment]
因不是有偿对第三方推广, 不处理.
