### ISSUE TITLE
10443 端口网站连结消失

### ISSUE THREAD

**Issue by s911415** [easylist/easylistchina#209]
### 什么问题 What happens?
我有个内部站台运行在 10443 端口，发现连接被阻拦
想了解 `##a[href*=":10443/"]` 这规则没有指定域名的原因?
是否会过于宽松?

https://github.com/easylist/easylistchina/blob/7798a6270ff2916c236f0ba66ac8927b9b0f35d6/easylistchina.txt#L1379

### 列出你启用的列表 List Subscriptions you're using:
[easylistchina](https://github.com/easylist/easylistchina)

### 你的设置 Your settings
- 浏览器/版本 Browser/version: Chrome
- 过滤工具/版本 Adblock Extension/version: Adblock/4.46.2

**Comment by cjx82630** [comment]
30分钟后更新. 01c1ded718a93c681f1b2a2d1733455bf74b36c8
Fixed.Please manually update in 30 minutes.
