### ISSUE TITLE
mooc tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylistchina#21]
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php?actype=start
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php?actype=end

```
||i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php^
or
/mooc/controllers/course_ajax.php (超過一所學校使用此系統)
/controllers/course_ajax.php ?
```

![image](https://user-images.githubusercontent.com/75058881/111773241-e32b7b80-88e8-11eb-9b4f-efb571a90522.png)
![image](https://user-images.githubusercontent.com/75058881/111773264-ec1c4d00-88e8-11eb-842d-6707041d8774.png)
![image](https://user-images.githubusercontent.com/75058881/111784055-e5480700-88f5-11eb-8d19-93215c2cb890.png)

**Comment by c2xusnpq6** [comment]
https://www.google.com/search?q=%22mooc%2Fcontrollers%22

**Comment by cjx82630** [comment]
Easyprivacy https://github.com/easylist/easylist/issues/7457
