### ISSUE TITLE
正常图片被误屏蔽

### ISSUE THREAD

**Issue by vapehacker** [easylist/easylistchina#210]
### 什么问题 What happens?

我的站点中，正常评论的用户头像被拦截。被误屏蔽的内容大概是这样的：
```html
<a class="user-info" id="info-link" href="https://space.bilibili.com/example">
	<img class="comment-avatar" id="avatar" src="https://example.com/proxy/avatar?url=https%3A%2F%2Fi2.hdslb.com%2Fbfs%2Fface%2F2a9cb394198b9243c12ab72b3063299f4d471088.jpg@32w_32h_1c_1s.webp">
</a>
```

能否修改一下规则，谢谢。

### 附注(列出有问题的规则,截图,建议等) Other details:

这条规则误屏蔽了用户头像：
https://github.com/easylist/easylistchina/blob/b00a76ff78376a7289974ffe02a1296c3c9108e1/easylistchina.txt#L1390

其中， *hdslb.com* 是哔哩哔哩的 CDN 域名，这个匹配范围恐怕过大了。

这条规则与这些提交有关： 6accfb6227 08b24eafeb

应该屏蔽的广告内容类似这样：
```html
<a id="62b2f3da0b14a" target="_blank" href="/ad/007.html">
	<img id="62b2f3da0b14b" referrerpolicy="no-referrer" src="https://i0.hdslb.com/bfs/album/c44101c9c08e903198cb13d5d5b59a6200168f01.jpg" width="100%">
</a>
```

供参考的几点匹配建议：
- `width` / `referrerpolicy` 属性
- 针对 `src` 路径："/bfs/album/"，因为 "/bfs/face/" 是头像的路径，一般不会被上传横幅广告这样的较大尺寸图片。
- 匹配 `href` 中的 "/ad/*"
- 针对特定域名启用此规则

**Comment by cjx82630** [comment]
30分钟后更新. 2f553d4a2d74f46de55c970b00cb7d4c62f07ab0
Fixed.Please manually update in 30 minutes.
