### ISSUE TITLE
https://www.ktsf.com/

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistchina#211]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.ktsf.com/

### 什么问题 What happens?
Banner ads 
search for `https://chpremier.com` and `https://onlok.org`

### 列出你启用的列表 List Subscriptions you're using:
ABP + EasyList + EasyListChina

### 你的设置 Your settings
- 系统/版本 OS/version: macOS
- 浏览器/版本 Browser/version: Opera
- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:
**Suggested filter:**
`ktsf.com##a[href^="https://chpremier.com/"]`
`ktsf.com##a[href^="https://onlok.org/contact/pace/zh"]`

<img width="1183" alt="ktsf" src="https://user-images.githubusercontent.com/57706597/175413369-d1edfcd3-a0f0-4dae-99b3-6d0f8074225c.png">

**Comment by cjx82630** [comment]
30分钟后更新. 043920e97bbd6e5b83816f16efac03659484262e
Fixed.Please manually update in 30 minutes.
