### ISSUE TITLE
m.weibo.cn

### ISSUE THREAD

**Issue by asdfj2381k** [easylist/easylistchina#215]
### 列出存在问题的网址 List the website(s) you're having issues:
https://m.weibo.cn/status/LA4hutWmB?jumpfrom=weibocom

### 什么问题 What happens?
![image](https://user-images.githubusercontent.com/56584082/176590060-5fc73364-a4f4-4b86-9edf-266a9f3bda62.png)

iOS safari

**Comment by cjx82630** [comment]
30分钟后更新 97c05a78a1170a200b9452fbd469217c9c06b319
Fixed.Please manually update in 30 minutes.

**Comment by asdfj2381k** [comment]
@cjx82630 
这种类型的广告在手机网页上层出不穷，他们只要更新一下就可以绕过屏蔽规则。

如果我想根据图片大小去屏蔽，应该怎么写这个规则？

**Comment by asdfj2381k** [comment]
比如，这个图片的PX就是 333*79.33

我想把所有网页里面这个大小的图片都屏蔽掉，应该怎么写？

**Comment by cjx82630** [comment]
没办法. 出现广告后才能处理. 规则教程 https://help.eyeo.com/adblockplus/how-to-write-filters
