### ISSUE TITLE
Hello, look, is it a manslaughter?

### ISSUE THREAD

**Issue by V2RaySSR** [easylist/easylistchina#216]
### 列出存在问题的网址 List the website(s) you're having issues:
v2rayssr.com##a[href*="goii.cc"]
### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:
Hello, boss, I am a webmaster and a YouTuber. This is the jump link in my blog. Of course, you are here for the customer's experience. But you can actually go to the website to see, except for Google Adsense ads, I don't have any ads that affect customer experience. goii.cc, this short link, is just a private website built by me when I introduce products to customers in a YouTube video, in order to facilitate customers' memory (because many product websites are constantly changing domain names), this goii.cc .cc is not open to anyone for shortening business! However, it is fatal to disable all the jumps of goii.cc in the blog. Goii does not have any advertising properties. Please go to the website to have a look! If not, please reply! I take the liberty to ask, what other methods can I use to recover! Because this is deadly. . .

**Comment by cjx82630** [comment]
Thas is indeed an advertisement. If you think the ad is acceptable, you can check it out https://adblockplus.org/en/acceptable-ads

**Comment by V2RaySSR** [comment]
OK, I will revise the advertisements on the site as soon as possible in accordance with the standards of acceptable advertisements, but there is a v2rayssr.com##.slider-4-box1 on the homepage of the website, please remove it, I will not revise this, I will modify all relevant advertising image information immediately, but this rule v2rayssr.com##.slider-4-box1 affects the style of the website. Thanks for your contribution to this area

**Comment by V2RaySSR** [comment]
01 Text Ads
Text ads designed with excessive use of colors and/or other elements to grab attention are not permitted.
02 Image Ads
Static image ads may qualify as acceptable, according to an evaluation of their unobtrusiveness based on their integration on the webpage.

**Comment by cjx82630** [comment]
30分钟后更新 f78ececb33cc9e1a0664e7cf23259e8de1127314
Temporarily removed filters.Please manually update in 30 minutes.

**Comment by V2RaySSR** [comment]
I will complete all the rectification of the website as soon as possible to ensure that each advertisement has a reminder and meets the "acceptable advertisement", thank you boss! Thanks for your hard work!
