### ISSUE TITLE
您好，这个广告是符合您这边所说的“可接受的广告”的！

### ISSUE THREAD

**Issue by V2RaySSR** [easylist/easylistchina#219]
### 列出存在问题的网址 List the website(s) you're having issues:
您好，v2rayssr.com 
首页的 
v2rayssr.com##.slider-4-box1 
v2rayssr.com###b2-widget-html-12
这个广告，我按照您这边提供的“可接受广告”的标准进行修改了。

### 什么问题 What happens?
这个广告是一个静态的图片广告啊，大小也都符合您这边的相关标准。还特地的在广告图片中说明了“这是一个广告”！
难道是因为带了超链接吗？“可接受的广告”条款里面说的“静态图片广告”是不能带超链接的吗？我不太清楚，若是因为这个原因屏蔽了，我可以按照社区的标准进行修改！
只是，首页的这个图片屏蔽了以后，导致PC端的样式很不美观，希望能给出意见！

### 列出你启用的列表 List Subscriptions you're using:
[Adblock Plus 2.0]
! Checksum: YxDQ3ZSr8QYXrZWdvFXuTg
! Version: 202207070105
! Title: EasyList China+EasyList
! Last modified: 07 Jul 2022 01:05 UTC

### 你的设置 Your settings

- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 

- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:
这个图片在里面已经标注了，这个是一个广告，已经按照标准提醒了啊！是否不带超链接才可以？若是如此，我会立即修改！
<img width="332" alt="截屏2022-07-07 09 48 41" src="https://user-images.githubusercontent.com/59167743/177672786-253982fa-d7e3-4c04-aebc-02a6eb4f6d34.png">
<img width="266" alt="截屏2022-07-07 09 19 39" src="https://user-images.githubusercontent.com/59167743/177670664-7f53d9a7-3ded-4f98-b807-2a5e5d999214.png">

**Comment by cjx82630** [comment]
符合可接受广告后,要到此申请, https://adblockplus.org/zh_CN/acceptable-ads#get-allowlisted 通过后会加入可接受广告的白名单. 属于与Easylist china不同的列表. 详细看前面地址

**Comment by V2RaySSR** [comment]
好的 首先我先把图片的超链接去掉 

去掉超链接是否就是正常展示了？

**Comment by cjx82630** [comment]
白名单会放置于这个列表  https://easylist-downloads.adblockplus.org/exceptionrules.txt

**Comment by V2RaySSR** [comment]
<img width="1457" alt="截屏2022-12-07 21 33 22" src="https://user-images.githubusercontent.com/59167743/206196751-27340339-fbff-4567-9ffe-5a00eaee9159.png">
我已经申请了啊。。是你们这边拦截的每一个广告，都需要申请可接受吗？您在看看您拦截的内容，真的只是网站内容啊，累累计计已经申请半年了。

**Comment by V2RaySSR** [comment]
若可以的话，您能帮忙写一个规则吗（一楼拦截的两个图片）？

我直接把规则报到“可接受的广告”那里去，因为我也不是很会写，所以交流起来有点问题。
