### ISSUE TITLE
请问，若是下面图片，不带超链接，或是图片链接站内文章，会被屏蔽吗？

### ISSUE THREAD

**Issue by V2RaySSR** [easylist/easylistchina#223]
列出存在问题的网址 List the website(s) you're having issues:
您好，v2rayssr.com
首页的
v2rayssr.com##.slider-4-box1
v2rayssr.com###b2-widget-html-12
这个广告，我按照您这边提供的“可接受广告”的标准进行修改了。

这个图片在里面已经标注了，这个是一个广告，已经按照标准提醒了啊！是否不带超链接才可以？若是如此，我会立即修改！

########################################
<img width="332" alt="177672786-253982fa-d7e3-4c04-aebc-02a6eb4f6d34" src="https://user-images.githubusercontent.com/59167743/178000713-72c8428f-5a0e-4abe-adbd-42285605f469.png">
<img width="266" alt="177670664-7f53d9a7-3ded-4f98-b807-2a5e5d999214" src="https://user-images.githubusercontent.com/59167743/178000722-aa0c8014-ae29-41f4-8397-902645c13b19.png">
########################################

对于上次您的回复，我看了下，好像，要申请“符合要求的广告”需要广告商去操作什么什么的，也不知道需要不需要付费。
但是，这个是我自己做的广告，我不知道需要怎么操作才好啊，目前，网站的样式，已经被插件影响了，我需要得到您这边的回复去解决这个问题。

也许您这边认为只是保存规则这么简单的一个事情，对于我来说，真心的致命的
所以，我真心的只是想知道，就这样的图片，应该怎么放才合适，是不能放超链接吗？链接站内的文章行不行啊？
若是可行的话，我就马上更改为站内的链接文章，感谢您的回复！

**Comment by cjx82630** [comment]
中文列表只拦截广告, 可接受广告列表只放行可接受广告, 这是两个各自独立的列表. 如果你的广告被前者拦截了, 可通过向后者申请来加白名单, 对于个人网站来说是免费的.

**Comment by V2RaySSR** [comment]
那，若是图片不放超链接链接到站外，连接到站内文章，可以吗？“可接受广告”，外语，不好沟通。。。

**Comment by cjx82630** [comment]
评测文章, 内附地址, 可能不拦截. 比如 https://www.ithome.com/ 的首页就有一些评测文章

**Comment by V2RaySSR** [comment]
好的，BOSS，我首先把超链接去掉。您这边更新相关的规则。我后去去申请“可接受的广告”

**Comment by V2RaySSR** [comment]
> 检举文章, 内附地址, 可能不阻止。[https://ithome.com/](https://www.ithome.com/)的一些首页www.ithome.com/

我已经把上面的广告：

v2rayssr.com##.slider-4-box1
v2rayssr.com###b2-widget-html-12

改为了站内评测文章，多谢，请更改规则。感谢BOSS！真心谢谢你的帮助，麻烦你了！

**Comment by cjx82630** [comment]
广告的定义是"有偿对第三方推广", 即在网站列出第三方链接, 并收到报酬. 这些广告会被中文列表拦截, 但有例外: 比如某些评测文章虽然有第三方链接, 并收到报酬, 但被拦截的话会造成读者困惑, 说明第三方链接是文章内容, 不适宜过滤. 所以你把有第三方推广链接的站内文章放在左侧, 随着翻页会消失, 看作是网站内容. 但把有第三方推广链接的站内文章固定在每个页面的某处, 就有明显的推广意图, 看作是要过滤的广告. 这些广告如果没有侵略性, 所以可以申请在可接受广告列表加白名单.

**Comment by V2RaySSR** [comment]
> 广告的定义是"有偿对第三方推广", 即在网站列出第三方链接, 并收到报酬. 这些广告会被中文列表拦截, 但有例外: 比如某些评测文章虽然有第三方链接, 并收到报酬, 但被拦截的话会造成读者困惑, 说明第三方链接是文章内容, 不适宜过滤. 所以你把有第三方推广链接的站内文章放在左侧, 随着翻页会消失, 看作是网站内容. 但把有第三方推广链接的站内文章固定在每个页面的某处, 就有明显的推广意图, 看作是要过滤的广告. 这些广告如果没有侵略性, 可以申请在可接受广告列表加白名单.

好的，我已经按照 https://www.zhujiceping.com/ 这个网站的标准，重新定义了。您可以检查一下，若是没有问题，能更改规则吗？
v2rayssr.com##.slider-4-box1
v2rayssr.com###b2-widget-html-12
