### ISSUE TITLE
zoukankan.com自动打开腾讯云

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#224]
### 列出存在问题的网址 List the website(s) you're having issues:
http://t.zoukankan.com/lexus-p-2756690.html

### 什么问题 What happens?
打开该网址，鼠标点击网页空白处会自动打开腾讯云销售界面。
似乎只会触发一次，清除cookie后刷新会再次出现。

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10
- 浏览器/版本 Browser/version: Firefox 102
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.43.0

**Comment by cjx82630** [comment]
30分钟后更新 c391966c7e354ec69a06a901ebbc16f8c3727ec5
Fixed.Please manually update in 30 minutes.
