### ISSUE TITLE
可接受的广告遥遥无期！

### ISSUE THREAD

**Issue by V2RaySSR** [easylist/easylistchina#225]
### 列出存在问题的网址 List the website(s) you're having issues:

v2rayssr.com##.slider-4-box1
v2rayssr.com###b2-widget-html-12

这两个广告分别链接了站内的文章，按道理来说，不应该作为广告被屏蔽啊。
很多主机厂商的评测文章，若是屏蔽了产品图片，那么，站点就废了啊。。

类似 https://www.zhujiceping.com/  这样的。是吧。

另外，这个广告是人家恶意举报的。我不认为这两个广告是不可接受的。真的。您有空可以看看。感谢！

**Comment by cjx82630** [comment]
zhujiceping.com也是要拦截的.
