### ISSUE TITLE
Broken timestamp in the metadata

### ISSUE THREAD

**Issue by Alex-302** [easylist/easylistchina#226]
### 什么问题 What happens?

`! Last modified: %timestamp%`

**Comment by cjx82630** [comment]
@Alex-302 Could you be more specific???

**Comment by Alex-302** [comment]
`%timestamp%` instead of time value :)

**Comment by cjx82630** [comment]
It was not required to change since [the first place](https://hg.adblockplus.org/easylistchina/file/6f140ef014e8/easylistchina.txt)
