### ISSUE TITLE
新增拦截

### ISSUE THREAD

**Issue by hyperpxy** [easylist/easylistchina#228]
### 列出存在问题的网址 List the website(s) you're having issues:
https://audit.qiuwen.wiki/analytics.js

### 什么问题 What happens?
跟踪网站，没有被拦截

### 列出你启用的列表 List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak 
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
EasyList China

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10
- 浏览器/版本 Browser/version: Chrome 103
- 过滤工具/版本 Adblock Extension/version: UBO 1.43.0

### 附注(列出有问题的规则,截图,建议等) Other details:
访问 https://www.qiuwenbaike.cn 和 https://www.qiuwen.wiki 出现

**Comment by cjx82630** [comment]
只处理广告的问题. 而跟踪保护的问题, 请反馈到 https://github.com/easylist/easylist/issues 并英文描述
