### ISSUE TITLE
m.doujiaow2.com

### ISSUE THREAD

**Issue by asdfj2381k** [easylist/easylistchina#229]
https://m.doujiaow2.com/vodhtml/aihuijiazhikaixinsudi/
（类似的域名：m.doujiaow1.com;  m.doujiaoww.com;）  m.doujiao*.com

随便点几下，就会弹广告
![image](https://user-images.githubusercontent.com/56584082/185304477-8c214fce-315a-4b09-b26f-eacadc928839.png)

**Comment by cjx82630** [comment]
没发现广告, 你先试试更新规则.

**Comment by asdfj2381k** [comment]
更新之后确实没广告了

奇怪。  我刚刚发帖之前，明明已经更新过一次了。
