### ISSUE TITLE
jpvhub.com

### ISSUE THREAD

**Issue by asdfj2381k** [easylist/easylistchina#230]
https://www.jpvhub.com/cn/xyr376wzov/jav/%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95/%5B%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D-%5B%E7%84%A1%E7%A2%BC%E6%B5%81%E5%87%BA%5D-stars-229-%E3%81%84%E3%81%84%E3%81%AA%E3%82%8A%E6%B8%A9%E6%B3%89%E6%97%85%E8%A1%8C-%E6%88%B8%E7%94%B0%E7%9C%9F%E7%90%B4

随便点几下播放，就会弹广告

iOS safari

**Comment by cjx82630** [comment]
此网站嵌入了英语网站视频, [应反馈到此](https://github.com/easylist/easylist/issues)
