### ISSUE TITLE
remove "cccpan.com,ys168.com,ysepan.com###zdy_wz0"

### ISSUE THREAD

**Issue by oldshensheep** [easylist/easylistchina#231]
### 列出存在问题的网址 List the website(s) you're having issues:
http://dfqshy.ysepan.com/

### 什么问题 What happens?
This line should be removed.
```
cccpan.com,ys168.com,ysepan.com###zdy_wz0
```
This is not an AD.
![image](https://user-images.githubusercontent.com/29306733/185743847-5fb584b9-7fa5-4e4c-9e77-a6f063dd2cb7.png)

**Comment by cjx82630** [comment]
30分钟后更新 f603f7516336d4598f930ec2012f8175278bfcb1
Fixed.Please manually update in 30 minutes.
