### ISSUE TITLE
百度广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#233]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://m.darenjiazu.com/article53156.html`

### 什么问题 What happens?
有广告

### 附注(列出有问题的规则,截图,建议等) Other details:
广告是从`c.mipcdn.com/static/v2/mip-ad/mip-ad.js`来的，easylistchina里有一条`||mipcdn.com^*/mip-*ad-`，匹配不上这个

**Comment by cjx82630** [comment]
30分钟后更新 55a17a3817b89210adffc09ce22188026f54fdb0
Fixed.Please manually update in 30 minutes.
