### ISSUE TITLE
[NSFW] https://boylove.cc/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#234]
### 列出存在问题的网址 List the website(s) you're having issues:
https://boylove.cc/

### 什么问题 What happens?
Banners

### 列出你启用的列表 List Subscriptions you're using:
EL + EL China

### 附注(列出有问题的规则,截图,建议等) Other details:
```
boylove.cc##.owl-carousel
boylove.cc##div[data-type="1"]
boylove.cc###fake_avivid_waterfall_webpush
```
<img width="466" alt="Screenshot 2022-09-02 at 10 52 18" src="https://user-images.githubusercontent.com/65717387/188103521-b8a87f90-8b2f-4272-8abc-1b4ee2b76a5e.png">

**Comment by cjx82630** [comment]
30分钟后更新 aae73b40bb171459297af526ab17ea806913cd28
Fixed.Please manually update in 30 minutes.
