### ISSUE TITLE
https://boyboy.cc/ (Mobile)

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#235]
### 什么问题 What happens?
Banner/gifs

### 列出你启用的列表 List Subscriptions you're using:
EL China

### 附注(列出有问题的规则,截图,建议等) Other details:

`###bl_mobile_float`
<img width="458" alt="Screenshot 2022-09-02 at 12 08 59" src="https://user-images.githubusercontent.com/65717387/188119020-65533a5f-8c01-469a-a619-b70523fb0328.png">

```
###index_content_ad
###index_aside_ad
```
<img width="410" alt="Screenshot 2022-09-02 at 12 21 51" src="https://user-images.githubusercontent.com/65717387/188119304-d248d330-b437-430a-8fcb-c96231fe29e0.png">

**Comment by cjx82630** [comment]
30分钟后更新 aae73b40bb171459297af526ab17ea806913cd28
Fixed.Please manually update in 30 minutes.
