### ISSUE TITLE
IT之家

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#236]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.ithome.com/`

### 什么问题 What happens?
首页广告

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://user-images.githubusercontent.com/81752398/188158745-3be512f1-5fbc-4b44-a48a-740c4068661f.png)

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes.
