### ISSUE TITLE
https://wap.dmshuwang.org/

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#239]
### 列出存在问题的网址 List the website(s) you're having issues:
https://wap.dmshuwang.org/xzhwzt/

### 什么问题 What happens?
(Mobile) video banners - footer

### 列出你启用的列表 List Subscriptions you're using:
EL China

### 附注(列出有问题的规则,截图,建议等) Other details:
<img width="691" alt="Screenshot 2022-09-05 at 11 13 37" src="https://user-images.githubusercontent.com/65717387/188414478-eefd078a-ed3b-4652-bd3c-043361e95620.png">

**Comment by cjx82630** [comment]
30分钟后更新 b03bc97be33364dc4f86c26d7ce18276a4248859
Fixed.Please manually update in 30 minutes.
