### ISSUE TITLE
Whois Data for Domains

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#24]
The whois data of the domains involved in the 1st-party rules, 3rd-party rules and popup rules were retrieved. 

Some domains with uncommon gTLDs such as .wang, .vip and others are not available. 

I remember you said this https://github.com/easylist/easylistchina/issues/8#issuecomment-791134480. So, this mostly serves as a plan B. 

[m_CHN_txt_2233901.xlsx](https://github.com/easylist/easylistchina/files/6289933/m_CHN_txt_2233901.xlsx)

**Comment by cjx82630** [comment]
Thanks for the data. How did you get this?

**Comment by sr093906** [comment]
Via in-house utility. The intention to provide the sheet is I hope it can make the maintenance easier as you could add new domain info into and remove expired domains from it and no longer need to look up such info online when needed.

**Comment by cjx82630** [comment]
in-house utility? And the invalid domain names have been removed
