### ISSUE TITLE
[NSFW] https://boylove.cc/ (Mobile)

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#240]
### 列出存在问题的网址 List the website(s) you're having issues:
https://boylove.cc/

### 什么问题 What happens?
Banners

### 列出你启用的列表 List Subscriptions you're using:
EL China

### 附注(列出有问题的规则,截图,建议等) Other details:
`boylove.cc##div[style="display: block"]` Seems to be working

**Comment by cjx82630** [comment]
30分钟后更新 8fef1c8cd285b9c7e9cb9b48c6ea030102a356c7
Fixed.Please manually update in 30 minutes.
