### ISSUE TITLE
神马推广

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#242]
### 列出存在问题的网址 List the website(s) you're having issues:
`http://m.xianzhaiwang.cn/`

### 什么问题 What happens?
页面中的神马搜索广告

### 附注(列出有问题的规则,截图,建议等) Other details:

![image](https://user-images.githubusercontent.com/81752398/189361920-bfc1c3e7-5a8f-4b34-95d2-cac0effd8e8d.png)

**Comment by cjx82630** [comment]
30分钟后更新 8cd1070253cc95e23990e70e227da4f6c81db7c3
Fixed.Please manually update in 30 minutes.
