### ISSUE TITLE
百度百科白名单

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#247]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://baike.baidu.com/item/%E6%99%AE%E9%80%9A%E8%AF%9D/161653`

### 什么问题 What happens?

手机浏览器打开百度百科，页面底部有百度的自我推广，而easylistchina里有一条规则`@@/adpic/*$domain=baike.baidu.com|czsrc.com|nieyou.com|ontheup.com.tw|zform.net`，放行了部分自我推广图片。

![image](https://user-images.githubusercontent.com/81752398/189568567-769066a0-e219-4b95-bba0-59ffc2641dd2.png)

easylist的[policy](https://easylist.to/pages/policy.html)有这样的表述：

> Self-promotion should not be specifically removed by EasyList, although equally should not be allowed if it is blocked.

所以这种自我推广不应该加白名单？

**Comment by cjx82630** [comment]
这是内容.
