### ISSUE TITLE
scrollbar blocked on ezone.ulifestyle.com.hk

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistchina#252]
### 列出存在问题的网址 List the website(s) you're having issues:
https://ezone.ulifestyle.com.hk/article/3351534/504

### 什么问题 What happens?
scrollbar blocked on subdomain **ezone.ulifestyle.com.hk** 
(doesn't seem to be blocked on other ulifestyle sudomains)

### 列出你启用的列表 List Subscriptions you're using:
ABP + EasyList 

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:
**Filter causing the issue is in EasyList:** 
`-contrib-ads.$~stylesheet`

**Suggested filter:** 
`@@||cdn.jsdelivr.net/combine/npm/video.js@7/dist/video.min.js$domain=ezone.ulifestyle.com.hk`
or
`@@||cdn.jsdelivr.net/combine/npm/video.js@7/dist/video.min.js,npm/video.js@7/dist/lang/zh-TW.min.js,npm/videojs-contrib-ads@6/dist/videojs-contrib-ads.min.js,npm/videojs-ima@1`

![scrolbar2](https://user-images.githubusercontent.com/57706597/190133449-f9840c88-d4c7-40df-8180-f67a4eefdd6d.png)
![scrolbar3](https://user-images.githubusercontent.com/57706597/190133472-495292fb-b8fe-48e2-8b99-476a15445ee3.png)

**Comment by cjx82630** [comment]
Please subscribe to [EasyList China](https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt)
