### ISSUE TITLE
误杀

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#253]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://wap.99zuowen.com/xiaoxuezuowen/sannijixiejing/1005181.html`

### 什么问题 What happens?

这个网站被整个拦截了，没有必要

### 附注(列出有问题的规则,截图,建议等) Other details:

https://github.com/easylist/easylistchina/blob/e8fcefac1fdbc38a24118207ca07295fd032999a/easylistchina.txt#L1982
https://github.com/easylist/easylistchina/blob/e8fcefac1fdbc38a24118207ca07295fd032999a/easylistchina.txt#L10725

**Comment by cjx82630** [comment]
30分钟后更新 c3462cf4349cfedaacdb1cb8f72c079f9c9a15d7
Fixed.Please manually update in 30 minutes.
