### ISSUE TITLE
腾讯视频新版网页广告

### ISSUE THREAD

**Issue by Hill-98** [easylist/easylistchina#254]
v.qq.com##[dt-params*="business=ad"]:remove()

新版网页目前正在灰度测试，访问时不一定会是。

[截图](https://i.imgur.com/b5eWhWk.jpeg)

**Comment by cjx82630** [comment]
看上去是电视版,无法重现.

**Comment by Hill-98** [comment]
不是电视版，是灰度测试的网页版本，有时候需要清除缓存和Cookies刷新好几遍才会触发。
