### ISSUE TITLE
能不能屏蔽手机浏览器上百度自动跳转应用商店

### ISSUE THREAD

**Issue by Waylon-Zhu** [easylist/easylistchina#26]
使用三星浏览器访问百度百家号会自动跳转应用商店下载百度，目前三星浏览器专用Adblock plus无法拦截。
拦截规则是||mbdp02.bdstatic.com^

**Comment by cjx82630** [comment]
不过滤自我推广. 可以试试订阅 https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
