### ISSUE TITLE
风车动漫

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#260]
### 列出存在问题的网址 List the website(s) you're having issues:

```
https://m.dm530p.link/view/23093.html
https://m.37ws.com/vod/detail/id/19488.html
http://www.nblxzl.com/dongman/16188.html
```

### 什么问题 What happens?
移动端访问有广告

**Comment by cjx82630** [comment]
你用什么浏览器, 过滤工具?

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes.
