### ISSUE TITLE
芒果TV 误杀

### ISSUE THREAD

**Issue by shellmingqu** [easylist/easylistchina#270]
### 列出存在问题的网址 List the website(s) you're having issues:
 www.mgtv.com

### 什么问题 What happens?
```
##a[target="_blank"] > img[src*="hitv.com"]
```
影响正常图片展示

### 你的设置 Your settings
- 系统/版本 OS/version:  All
- 浏览器/版本 Browser/version: All
- 过滤工具/版本 Adblock Extension/version: All

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://user-images.githubusercontent.com/111272138/194792779-cd0dff8d-048b-4111-9d1e-6b866fd992ce.png)

**Comment by cjx82630** [comment]
30分钟后更新 a5547ceb8ffccd13113ffdf463047a66d2e9d3f1
Fixed.Please manually update in 30 minutes.
