### ISSUE TITLE
a-i-l-s-a.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#272]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.a-i-l-s-a.com/vol10noSpecial/mitigating-urban-heat-island-through-green-roofs/`

### 什么问题 What happens?
页面两侧广告

**Comment by cjx82630** [comment]
30分钟后更新 eacbc4353650e6887e87d47a1e561095624278bd
Fixed.Please manually update in 30 minutes.
