### ISSUE TITLE
xinzhi.wenda.so.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#276]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://xinzhi.wenda.so.com/m/a/1664350821200124`

### 什么问题 What happens?
正文图片下方购物广告

**Comment by cjx82630** [comment]
30分钟后更新 76ea2d5b00b5cf78702354ce59995594b8d6da96
Fixed.Please manually update in 30 minutes.
