### ISSUE TITLE
muzhuangnet.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#280]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.muzhuangnet.com/show/101867.html`

### 什么问题 What happens?
移动端访问，页面底部有广告

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://user-images.githubusercontent.com/81752398/197943264-647ad333-6b5b-4439-861f-ca8e87e3b27a.png)

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes.
