### ISSUE TITLE
cooboys.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#281]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://shuma.cooboys.com/shuma/202210/473564.html`

### 什么问题 What happens?
移动端访问有广告

**Comment by cjx82630** [comment]
30分钟后更新 61e4dce598e552f7f6e2751c8b4ed03d0f2719ea
Fixed.Please manually update in 30 minutes.
