### ISSUE TITLE
广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#287]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://m.wannianli8.com/arc3996192`
`https://www.zjkhuiyu.com/a/DeomVv.html`

### 什么问题 What happens?
移动端访问有广告

**Comment by cjx82630** [comment]
30分钟后更新 1b98ee847a552ddf285f5578b320965be02a0a32
Fixed.Please manually update in 30 minutes.
