### ISSUE TITLE
www.le.com

### ISSUE THREAD

**Issue by ilvjyw** [easylist/easylistchina#288]
详情看这里
https://github.com/AdguardTeam/AdguardFilters/issues/134776

**Comment by cjx82630** [comment]
30分钟后更新 63e26e8ffe501e5f27c7ddde75b86ea3307f023e
Fixed.Please manually update in 30 minutes.

**Comment by ilvjyw** [comment]
谢大佬

**Comment by ilvjyw** [comment]
@cjx82630  一样的问题
