### ISSUE TITLE
aizhan.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#289]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.aizhan.com/cha/www.baidu.com/`

### 什么问题 What happens?
移动端访问有广告

### 附注(列出有问题的规则,截图,建议等) Other details:
`||tt.027dir.com^`

![image](https://user-images.githubusercontent.com/81752398/202638200-528e4795-159a-4a8a-b902-a85dc2365842.png)

**Comment by cjx82630** [comment]
30分钟后更新 1fc4e15a4f4aa0ad4649a31bdf4c8d0b10030920
Fixed.Please manually update in 30 minutes.
