### ISSUE TITLE
这个不是广告，被误屏蔽，请移除下，谢谢  

### ISSUE THREAD

**Issue by zhangyt93** [easylist/easylistchina#29]
![image](https://user-images.githubusercontent.com/17688171/121330381-8a4c0c00-c948-11eb-8d0d-89b1ad781a92.png)

500.com##a[href*="sanyol.cn"]

这个不是广告，是网站主要功能链接，被误屏蔽，请移除下，谢谢

**Comment by cjx82630** [comment]
属于第三方链接, 且标明是广告

**Comment by zhangyt93** [comment]
![image](https://user-images.githubusercontent.com/17688171/121455814-b06cbd00-c9d7-11eb-89d7-087b63dc5d46.png)
是第三方链接，但并不是广告，是网站的基础功能组成部分，屏蔽后导致正常功能缺失，咨询文章列表内容缺失，硬要说有广告的话，中部轮播banner才是广告部分

**Comment by cjx82630** [comment]
建议不要把广告混在内容里.

**Comment by zhangyt93** [comment]
目前网站部分内容是由第三方链接提供的，并不是广告，可以审查下，现在直接用“500.com##a[href*="sanyol.cn"]”规则，导致正常的资讯功能也用不了，直接误杀了，可以用更精确的规则来屏蔽广告内容。谢谢。

**Comment by zhangyt93** [comment]
“500.com##a[href*="sanyol.cn"]”这个规则确实是一刀切了，推荐文章也躺枪隐藏掉了，建议用“.slide-wrap”来屏蔽中部广告位，

**Comment by zhangyt93** [comment]
目前使用这个规则“500.com##a[href*="sanyol.cn"]”，导致m.500.com首页大部分网站元素都被隐藏了，内容缺失严重，你可以对比下看看。谢谢。

**Comment by swling** [comment]
这玩意就是个流氓。别和他扯淡了，自己想办法吧。

**Comment by swling** [comment]
补充一句，为什么说是流氓。
 - 第一，我坚定支持用户有选择安装屏蔽广告插件的权利。
 - 第二，于此对等的，网站方也应该有权利对屏蔽广告的浏览者采取针对性措施，包括限制提供内容甚至完全拒绝访问。
 
但是这个插件的规则，完全无视站长的权利。也就是说，站长连检测用户屏蔽广告，并采取拒接提供内容的权利它都会不遗余力的干扰。老话说，断人财路，如杀人父母。谨代表广大站长，给插件开发者，送上深深的祝福。

**Comment by cjx82630** [comment]
@swling sanyol.cn是第三方广告, 所以被屏蔽.  另外你说的检测问题: 如果能通过放行某脚本等白名单的方式避免检测, 会在中文规则更新. 如果白名单也避免不了检测的时候, 中文规则会忽略该网站, 让用户自行选择离开还是整站加白. 例子见pcbeta.com

**Comment by swling** [comment]
> 
> 
> @swling sanyol.cn是第三方广告, 所以被屏蔽. 另外你说的检测问题: 如果能通过放行某脚本等白名单的方式避免检测, 会在中文规则更新. 如果白名单也避免不了检测的时候, 中文规则会忽略该网站, 让用户自行选择离开还是整站加白. 例子见pcbeta.com

那么问题来了，为什么要通过添加白名单的方式去阻挠站长检测广告屏蔽插件呢？这个行为的出发点是什么，理由是什么？

**Comment by cjx82630** [comment]
@swling 白名单是放行, 不是拦截.  放行你家的资源, 你会抱怨用户阻挠检测吗?

**Comment by swling** [comment]
> 
> 
> @swling 白名单是放行, 不是拦截. 放行你家的资源, 你会抱怨用户阻挠检测吗?

作为站长，我的需求很简单，希望能检测当前用户浏览器是否屏蔽了广告，并选择是否继续提供内容。但你们的规则一直在和站长这一点点需求做对抗，不是么？

**Comment by swling** [comment]
> 
> 
> @swling 白名单是放行, 不是拦截. 放行你家的资源, 你会抱怨用户阻挠检测吗?

比如，原本，添加一个 ads.js 就可以简单检测用户是否屏蔽了广告，并作出对应提示，但很快，你们的规则就会选择性地对这个脚本放行。从而让站长的检测行为失效。

**Comment by cjx82630** [comment]
你的警告信息是自我推广, 中文规则不会去拦截, 但加白名单没问题. 因为白名单没有拦截你家的资源.

**Comment by swling** [comment]
> 
> 
> 你的警告信息是自我推广, 中文规则不会去拦截, 但加白名单没问题. 因为白名单没有拦截你家的资源.

明白，总而言之，就是在所谓的规则内，尽可能和站长做对抗。

**Comment by cjx82630** [comment]
白名单没有拦截你的资源, 所以可以随意加 . 中文规则不会采取拦截的方式去除你的检测

**Comment by swling** [comment]
> 
> 
> > 你的警告信息是自我推广, 中文规则不会去拦截, 但加白名单没问题. 因为白名单没有拦截你家的资源.
> 
> 明白，总而言之，就是在所谓的规则内，尽可能和站长做对抗。

你这么说我倒是放心了，因为脚本被选择性加入白名单后，我采用的是，js创建广告元素来检测插件。倒是一直有效。

**Comment by swling** [comment]
> 
> 
> 白名单没有拦截你的资源, 所以可以随意加 . 中文规则不会采取拦截的方式去除你的检测

为了避免被你们的规则更新，甚至只能悄悄检测，过段时间再拦截，真不知道你是怎么想的，拦截广告可以，千方百计阻挠站长检测广告插件，真的是。。。自己摸着良心，好好想想吧。

**Comment by swling** [comment]
比如这个 pcBata 我看了网站的脚本，为了避免被你们的规则识别，煞费苦心写了一大堆。你自己想想，人家在写这些代码的时候，心里对你的祝福了么？

**Comment by cjx82630** [comment]
难道你不允许加白名单了?

**Comment by swling** [comment]
> 
> 
> 难道你不允许加白名单了?

你很适合去外交部工作呢。避重就轻。

**Comment by cjx82630** [comment]
> 比如这个 pcBata 我看了网站的脚本，为了避免被你们的规则识别，煞费苦心写了一大堆。你自己想想，人家在写这些代码的时候，心里对你的祝福了么？

那你想想用户看到广告有多痛苦, 我已经不看pcbeta了

**Comment by swling** [comment]
> 
> 
> > 比如这个 pcBata 我看了网站的脚本，为了避免被你们的规则识别，煞费苦心写了一大堆。你自己想想，人家在写这些代码的时候，心里对你的祝福了么？
> 
> 那你想想用户看到广告有多痛苦, 我已经不看pcbeta了

用户看到广告很痛苦，那就可以选择不看。我再三强调了，不是反对用户屏蔽广告了。而是反对你们对站长检测广告是否被拦截的阻挠

**Comment by swling** [comment]
> 
> 
> > 比如这个 pcBata 我看了网站的脚本，为了避免被你们的规则识别，煞费苦心写了一大堆。你自己想想，人家在写这些代码的时候，心里对你的祝福了么？
> 
> 那你想想用户看到广告有多痛苦, 我已经不看pcbeta了

用户可以选择屏蔽广告，站长可以选择屏蔽屏蔽广告的用户。明白我的诉求么？

**Comment by swling** [comment]
> 
> 
> > > 比如这个 pcBata 我看了网站的脚本，为了避免被你们的规则识别，煞费苦心写了一大堆。你自己想想，人家在写这些代码的时候，心里对你的祝福了么？
> > 
> > 
> > 那你想想用户看到广告有多痛苦, 我已经不看pcbeta了
> 
> 用户可以选择屏蔽广告，站长可以选择屏蔽屏蔽广告的用户。明白我的诉求么？

你当然心知肚明，不过揣着明白装糊涂罢了。

**Comment by cjx82630** [comment]
我前面说了, 再重申: 中文规则不会拦截自我推广, 包括检测, 但完全可以随意加白名单.

**Comment by swling** [comment]
> 
> 
> > 比如这个 pcBata 我看了网站的脚本，为了避免被你们的规则识别，煞费苦心写了一大堆。你自己想想，人家在写这些代码的时候，心里对你的祝福了么？
> 
> 那你想想用户看到广告有多痛苦, 我已经不看pcbeta了

而且你有没有想过，现在屁大一个网站，都要强行推广自己的APP，web都已经被搞成这样了，还在自相残杀。

**Comment by swling** [comment]
> 
> 
> 我前面说了, 再重申: 中文规则不会拦截自我推广, 包括检测, 但完全可以随意加白名单.

懂。这是你们的规则。但你在这个规则内，做了很多恶心事。

**Comment by swling** [comment]
> 
> 
> 我前面说了, 再重申: 中文规则不会拦截自我推广, 包括检测, 但完全可以随意加白名单.

真诚地建议，你可以去外交部工作呢

**Comment by cjx82630** [comment]
中文规则的使命是拦截广告, 你网站主是拼命显示广告. 两者是对立的. 如果你能选择温和的广告方式, 你可以去申请可接受广告项目.

**Comment by swling** [comment]
> 
> 
> 中文规则的使命是拦截广告, 你网站主是拼命显示广告. 两者是对立的. 如果你能选择温和的广告方式, 你可以去申请可接受广告项目.

我的网站整页就一个广告，还不是照样被针对性白名单，阻挠检测。
最后说一句，你知道现在有多少手机浏览器默认就是拦截广告的么？很多用户根本不知道自己拦截了广告，更不知道怎么取消拦截，最后只能购买花钱我们的去广告服务。
