### ISSUE TITLE
kanxis.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#290]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.kanxis.com/post/349802.html`

### 什么问题 What happens?
移动端访问有广告

**Comment by cjx82630** [comment]
你用手机端ABP? 无法应用部分规则,存在残留. 30分钟后更新 74e427c343251375c277d83610cd2091f5722890
Fixed.Please manually update in 30 minutes.
