### ISSUE TITLE
rujume.top误杀

### ISSUE THREAD

**Issue by hacamer** [easylist/easylistchina#291]
### 列出存在问题的网址 List the website(s) you're having issues:
rujume.top

### 什么问题 What happens?
![图片](https://user-images.githubusercontent.com/73057402/203473671-ac1b81fa-844b-47ae-b2a1-2debbd305270.png)
视频解析播放被拦截

### 列出你启用的列表 List Subscriptions you're using:
EasyListChina

### 你的设置 Your settings
- 系统/版本 OS/version: 安卓
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: X浏览器

### 附注(列出有问题的规则,截图,建议等) Other details:
建议
@@rujume.top/muiplayer
@@rujume.top/?url=
@@rujume.top/API.php

![图片](https://user-images.githubusercontent.com/73057402/203473727-9aec98dd-caa8-4a56-84e4-3d1716b2da7a.png)

问题发现者 ： @damengzhu

**Comment by cjx82630** [comment]
30分钟后更新 799bfe9cb0f909a8d03600766da3fbd5549233b2
Fixed.Please manually update in 30 minutes.
