### ISSUE TITLE
https://www.itdog.cn/ping/ 广告

### ISSUE THREAD

**Issue by hacamer** [easylist/easylistchina#294]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.itdog.cn/ping/

### 什么问题 What happens?
广告

### 列出你启用的列表 List Subscriptions you're using:
EasyList+EasyListChina

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 11 22H2 22623.1020
- 浏览器/版本 Browser/version: Firefox Nightly for Windows 109.0a1(2022-12-03) (64位)
- 过滤工具/版本 Adblock Extension/version: AdGuard For Windows 7.11.3

### 附注(列出有问题的规则,截图,建议等) Other details:

![图片](https://user-images.githubusercontent.com/73057402/205475826-f0dc7289-9a7e-49ba-b74f-6fe953b2f580.png)
![图片](https://user-images.githubusercontent.com/73057402/205475831-fb8ba602-4294-4493-a412-f03d33908182.png)

头部广告 `www.itdog.cn##.top_contents`
中部广告 `www.itdog.cn##[class*="gg_link"]`

![图片](https://user-images.githubusercontent.com/73057402/205475965-404da7f7-026f-4c3e-b756-169a3244ef66.png)
底部推广文字 `itdog.cn##.text-center`
不知道算不算在广告范畴内

**Comment by cjx82630** [comment]
早些时候已处理.请手动更新 
Fixed sometime ago.Please manually update now.
