### ISSUE TITLE
hk.yahoo.com

### ISSUE THREAD

**Issue by User6751** [easylist/easylistchina#296]
### 列出存在问题的网址 List the website(s) you're having issues:
https://hk.yahoo.com
https://hk.yahoo.com/home/%E9%BB%8E%E6%99%BA%E8%8B%B1%E6%AC%BA%E8%A9%90%E7%BD%AA%E6%88%90-%E7%BE%8E%E5%9C%8B%E5%8B%99%E9%99%A2%E6%89%B9%E5%88%A4%E5%88%91%E4%B8%8D%E5%85%AC-%E6%B8%AF%E5%BA%9C%E6%96%A5%E5%B9%B2%E9%A0%90%E5%8F%B8%E6%B3%95%E5%85%AC%E5%B9%B3%E5%AF%A9%E8%A8%8A-072532228.html

### 什么问题 What happens?
廣告

### 列出你启用的列表 List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Fanboy’s Annoyance
uBlock filters – Annoyances
EasyList China

### 你的设置 Your settings
- 系统/版本 OS/version: Android 10
- 浏览器/版本 Browser/version: Firefox Mobile 107.2.0
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.45.2

### 附注(列出有问题的规则,截图,建议等) Other details:
![20221211_172905](https://user-images.githubusercontent.com/120245025/206896330-44bb3b6d-c866-48e3-8b58-10f3790e0b7b.jpg)
![20221211_172923](https://user-images.githubusercontent.com/120245025/206896333-b6ba7bfa-5c67-4459-ac41-ff4fe155c74c.jpg)
/
![20221211_172848](https://user-images.githubusercontent.com/120245025/206896373-15482412-8954-42e4-b625-e8b7c5fac7fb.jpg)

**Comment by cjx82630** [comment]
Cannot reproduce the issue on Firefox Mobile with ubo.
