### ISSUE TITLE
Breaks Fitbit gallery

### ISSUE THREAD

**Issue by MLSci** [easylist/easylistchina#297]
### 列出存在问题的网址 List the website(s) you're having issues:
Fitbit gallery (in the app)

### 什么问题 What happens?
No connection

### 列出你启用的列表 List Subscriptions you're using:
oisd, fanboy's annoyance

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: 
Android 13
Chrome 108
NextDNS

### 附注(列出有问题的规则,截图,建议等) Other details:
STR:
Open Fitbit app
Tap profile avatar
Select device
Click "Gallery"

**Comment by cjx82630** [comment]
Could you reprodue the issue on browsers?

**Comment by MLSci** [comment]
> Could you reprodue the issue on browsers?

I don't think so. I tried adding the Fitbit.com domain to my allowlist but still to no avail
