### ISSUE TITLE
fwwang.cn

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#299]
### 列出存在问题的网址 List the website(s) you're having issues:
`http://fwwang.cn/xindetihuijinji/2022/1216/525038.html`

### 什么问题 What happens?
百度推广，购物网站推广

**Comment by cjx82630** [comment]
30分钟后更新 15b8372850c954820b9a6f787dfd112a8691fa2a
Fixed.Please manually update in 30 minutes.
