### ISSUE TITLE
多余的广告元素

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#30]
您好！
网址：http://tool.chinaz.com/tools/textencrypt.aspx?qq-pf-to=pcqq.c2c
![image](https://user-images.githubusercontent.com/66902050/121873554-14291a00-cd39-11eb-9667-3225d51f467d.png)

**Comment by cjx82630** [comment]
已处理.请30分钟后手动更新(点击ABP图标>齿轮>高级>更新)
