### ISSUE TITLE
fenxi.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#302]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.sohu.com/a/620353595_118778`

### 什么问题 What happens?
（因为DNS没有拦截到发现的）Chrome+uBlock添加这条规则`sohu.com#@#.left-bottom-float`以后，打开`https://www.sohu.com/a/620353595_118778`，左下角出现广告图片，图片链接为`https://s3m4.fenxi.com/galileo/2cd24954e9c9ce505f82ffdd567ba251.gif`，查看`https://fenxi.com`的证书，发现该域名属于奇虎360，证书的主题备用名称包括`fenxi.com`, `mvad.com`和已经被屏蔽的`mediav.com`，且有帖子`https://bbs.360.cn/thread-15889807-1-1.html`，因此请求屏蔽此域名。

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://user-images.githubusercontent.com/81752398/209295219-b9fc8ecb-8377-42a9-a141-1e4186fd2603.png)

![image](https://user-images.githubusercontent.com/81752398/209295243-e6392898-a692-4f03-a93c-ae26be07bc46.png)

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. c026cf7d9ac1e04b37240bdfa081859d2a31a450
