### ISSUE TITLE
[NSFW] www.52av.one

### ISSUE THREAD

**Issue by User6751** [easylist/easylistchina#304]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.52av.one/forum.php

### 什么问题 What happens?
點擊其中一個「區」時會自動彈出新分頁

### 列出你启用的列表 List Subscriptions you're using:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Quick fixes
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Fanboy’s Annoyance
uBlock filters – Annoyances
EasyList China

### 你的设置 Your settings
- 系统/版本 OS/version: Android 10
- 浏览器/版本 Browser/version: Firefox 108.1.0
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.46.0

### 附注(列出有问题的规则,截图,建议等) Other details:
![Screenshot_20221225-121704_Firefox](https://user-images.githubusercontent.com/120245025/209456827-a0388e4f-2472-4189-99cb-4f36d6386834.jpg)
![Screenshot_20221225-121649_Firefox](https://user-images.githubusercontent.com/120245025/209456830-d043985a-4cd2-4721-839c-41c785355d5e.jpg)
![Screenshot_20221225-121657_Firefox](https://user-images.githubusercontent.com/120245025/209456831-99062eed-4915-4738-87f2-d755f46d69d7.jpg)

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. 10832e2ea668cc5de4067fcdfb893f7bc15790d1
