### ISSUE TITLE
cardbaobao.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#306]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.cardbaobao.com/card/cardinfo/pinganxinyongka_7669.shtml`

### 什么问题 What happens?
百度推广

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. 19ab4c4db76b360055959c3d837a379d712e6c82
