### ISSUE TITLE
多余的广告元素&自我推广

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#31]
您好！
网址：https://www.last.fm/zh/home
![image](https://user-images.githubusercontent.com/66902050/122343134-f269a600-cf77-11eb-87dc-3a9d8b4ebfe3.png)

**Comment by shenzhiming88** [comment]
@cjx82630 您好！
这个网站应该需要账号，于是我用临时邮箱注册了一个账户供您测试
账号：zfsqla38916@chacuo.net
密码：123abc@

**Comment by cjx82630** [comment]
不是弹窗, 悬浮, 所以不处理 你可以自定义隐藏.

**Comment by shenzhiming88** [comment]
> 不是弹窗, 悬浮, 所以不处理 你可以自定义隐藏.

您好！
那上面那个`不想看到广告？马上升级`应该处理一下吧，谢谢！

**Comment by shenzhiming88** [comment]
@cjx82630 您好！我觉得上面那个广告占位符应该去除，这属于多余的广告内容

**Comment by shenzhiming88** [comment]
fixed in https://github.com/easylist/easylist/commit/f8d58a5769d6122630b244544998711f7d7d6a06
