### ISSUE TITLE
openwrt 上更新规则后导致dnsmasq 启动失败

### ISSUE THREAD

**Issue by Yanel85** [easylist/easylistchina#310]
Fri Jan 27 16:26:07 2023 daemon.crit dnsmasq[9541]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Fri Jan 27 16:26:07 2023 daemon.crit dnsmasq[9541]: FAILED to start up

openwrt on R2s 
使用 广告屏蔽大师 Plus+
更新规则后导致dnsmasq 启动失败

**Comment by cjx82630** [comment]
[Easylist](https://easylist-downloads.adblockplus.org/easylist.txt), [Easyprivacy](https://easylist-downloads.adblockplus.org/easyprivacy.txt)也是如此

**Comment by Karmylr** [comment]
adbyby有问题是正常的
