### ISSUE TITLE
i.328888.xyz被误ban

### ISSUE THREAD

**Issue by Franinc** [easylist/easylistchina#314]
`i.328888.xyz`目前是imgloc图床的CDN域名，直接访问[https://i.328888.xyz/](https://i.328888.xyz/)就会有提示。

但1583行的规则`||328888.xyz^ `把它误ban了
https://github.com/easylist/easylistchina/blob/f7d27a7b4bace55a9755cd1f2f6da268021cd13a/easylistchina.txt#L1583

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. c613d321d2c93cf038b465b2060cfa3626cdc005
