### ISSUE TITLE
Ads on `https://myhappy8.com/`

### ISSUE THREAD

**Issue by eporubin** [easylist/easylistchina#316]
### 列出存在问题的网址 List the website(s) you're having issues:
https://myhappy8.com/

### 什么问题 What happens?
I see a lot of ads on this page

### 列出你启用的列表 List Subscriptions you're using:
ABP Filters
Easy List 
ChinaEasyList +Easy List

### 你的设置 Your settings
- 系统/版本 OS/version:  macOS
- 浏览器/版本 Browser/version: Google Chrome 111.0.5563.64 
- 过滤工具/版本 Adblock Extension/version: Ad Block Plus 3.16.2

### 附注(列出有问题的规则,截图,建议等) Other details:
This filter seems to work for me `##.ads-frame`
![image](https://user-images.githubusercontent.com/33602691/226992127-9cef229f-b773-46de-9176-76ca44c30a8c.png)

**Comment by cjx82630** [comment]
Looks like that is a fake site.
