### ISSUE TITLE
百度搜索移动端导航栏被误屏蔽

### ISSUE THREAD

**Issue by fxzxmicah** [easylist/easylistchina#320]
### 列出存在问题的网址 List the website(s) you're having issues:
https://m.baidu.com/from=1013966u/s?word=%E7%9F%A5%E4%B9%8E

### 什么问题 What happens?
最上面的导航栏被误屏蔽

### 列出你启用的列表 List Subscriptions you're using:
easylistchina
easylist

### 你的设置 Your settings
- 系统/版本 OS/version: 安卓13
- 浏览器/版本 Browser/version: via 4.5.1
- 过滤工具/版本 Adblock Extension/version: via

### 附注(列出有问题的规则,截图,建议等) Other details:
开启后：
![Screenshot_20230329_083931](https://user-images.githubusercontent.com/48860358/228397203-0d630ff6-8d25-4c3c-aadc-01ced1a50478.jpg)
禁用规则后是正常的：
![Screenshot_20230329_084159](https://user-images.githubusercontent.com/48860358/228397478-fd7cd9c6-eb75-4b3b-ac12-104967591991.jpg)

**Comment by cjx82630** [comment]
2a04acedffac50a2883251269dc8643dd75da712

**Comment by fxzxmicah** [comment]
感觉不是最好的，但是似乎也只能这样了。

**Comment by fxzxmicah** [comment]
@cjx82630 你好，抱歉打扰，但是经过检查，导航栏并没有被屏蔽，只是由于字体为白色而背景被屏蔽导致白色的字体在白色的背景下没有显示出来。所以希望能够撤销这个commit。抱歉。

**Comment by fxzxmicah** [comment]
![Screenshot_20230429_212621](https://user-images.githubusercontent.com/48860358/235305352-c001c4fd-49bf-4467-b4cf-8193bd4f6533.jpg)
另外，希望能够将品牌广告下面的两条广告也一起屏蔽掉。
