### ISSUE TITLE
baidu搜索页面广告无法消除

### ISSUE THREAD

**Issue by redflowerfu** [easylist/easylistchina#321]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.baidu.com/s?wd=chrome%20rss&pn=10

### 什么问题 What happens?
搜索结果页面存在广告

### 列出你启用的列表 List Subscriptions you're using:
列表1（Opera）：
EasyList
EasyList China
cjx-annoyance
EasyPrivacy
NoCoin (Cryptocurrency Mining Protection) 

列表2（XBrowser）：
EasyList China
core-rule-cn

### 你的设置 Your settings
- 系统1/版本 OS/version:  Windows 7 
- 浏览器1/版本 Browser/version:  Opera 95.0.4635.80 
- 过滤工具1/版本 Adblock Extension/version:  Opera内置过滤插件

- 系统2/版本 OS/version:  MIUI 11.1.27 ( Android 10 )
- 浏览器2/版本 Browser/version:  XBrowser 3.8.5
- 过滤工具2/版本 Adblock Extension/version:  XBrowser内置过滤工具

### 附注(列出有问题的规则,截图,建议等) Other details:
手动添加静态CSS规则后广告消失

**Comment by cjx82630** [comment]
请截图

**Comment by redflowerfu** [comment]
第一页有时候不会显示广告，但从第二页开始就有
![image](https://user-images.githubusercontent.com/37037690/229693760-6470d30e-5634-4dc2-b85b-e04bdd8bffb3.png)
![image](https://user-images.githubusercontent.com/37037690/229693956-e0d2259c-ccdb-46a9-b79a-27e158f1bfe5.png)

**Comment by redflowerfu** [comment]
F12里对应的块
![image](https://user-images.githubusercontent.com/37037690/229694798-3a4f7328-7c6b-49ff-95a3-76d06dcf6517.png)
![image](https://user-images.githubusercontent.com/37037690/229695290-9fe94708-fb4c-4d87-aaa9-7b3d1fa1b13a.png)

**Comment by cjx82630** [comment]
需要Adblock Plus 3.x加载[小脚本规则](https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt)才能拦截
