### ISSUE TITLE
chkaja.com

### ISSUE THREAD

**Issue by 462** [easylist/easylistchina#322]
### 列出存在问题的网址 List the website(s) you're having issues:
`chkaja.com`
`img.chkaja.com`

### 什么问题 What happens?
Falsely blocked. `chkaja.com` is a blog domain. `img.chkaja.com` is a image hosting domain.

### 列出你启用的列表 List Subscriptions you're using:
Easylist China

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10
- 浏览器/版本 Browser/version: Chrome 111.0.5563.65
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.48.4

### 附注(列出有问题的规则,截图,建议等) Other details:
https://github.com/easylist/easylistchina/blob/eb9244ad8f95899e3ec3b0bd17e179f17e8771b7/easylistchina.txt#L3134
https://github.com/easylist/easylistchina/blob/eb9244ad8f95899e3ec3b0bd17e179f17e8771b7/easylistchina.txt#L8195
Remove them from blacklist.

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. d3bcf48d46ced38e78c0f3c601f75028c1ba17a5
