### ISSUE TITLE
tv.libvio.cc

### ISSUE THREAD

**Issue by Karmylr** [easylist/easylistchina#324]
### 列出存在问题的网址 List the website(s) you're having issues:
https://tv.libvio.cc/

### 什么问题 What happens?
有广告

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://user-images.githubusercontent.com/69903376/231794583-997795bc-a7cf-4245-a55b-7654dc5356dc.png)

**Comment by cjx82630** [comment]
6ad2f8eb33b1b83af77b82c4d2e1fd8c2672ca70

**Comment by Karmylr** [comment]
@cjx82630 在easylistchina内的`libvio.me,smdyy.cc##.t-img-box`这一行加上libvio.cc好像更好？
