### ISSUE TITLE
广告反馈

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#325]
### 列出存在问题的网址 List the website(s) you're having issues:

```
https://zh-hans.ipshu.com/my_info
https://m.yhpdm.com/showp/21315.html
```

### 什么问题 What happens?
广告

### 你的设置 Your settings
- 系统/版本 OS/version: Android 12
- 浏览器/版本 Browser/version: Via 4.6.0
- 过滤工具/版本 Adblock Extension/version: Via built-in adblocker

**Comment by cjx82630** [comment]
e01628b50d44c466b759dec1b366602e1057c83c
a1e539be9addb0799695b02e022084dc5f22029b
