### ISSUE TITLE
ikandy.fun

### ISSUE THREAD

**Issue by Karmylr** [easylist/easylistchina#326]
### 列出存在问题的网址 List the website(s) you're having issues:
https://ikandy.fun

### 什么问题 What happens?
有广告

### 附注(列出有问题的规则,截图,建议等) Other details:
ikandy.fun#?#.stui-banner__item:has(a[href*=".html"])

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. 015062e6a320c050fe0657484d36817a02e4a9d7
