### ISSUE TITLE
www.novipnoad.com

### ISSUE THREAD

**Issue by Karmylr** [easylist/easylistchina#327]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.novipnoad.com/

### 什么问题 What happens?
有广告

### 附注(列出有问题的规则,截图,建议等) Other details:
##.col-md-2:has(img[title="广告"])

**Comment by cjx82630** [comment]
不能重现, 请截图

**Comment by cjx82630** [comment]
c55b2fbd099df4ab64157ea6eba815c63b210800
