### ISSUE TITLE
www.bilibili.com

### ISSUE THREAD

**Issue by Karmylr** [easylist/easylistchina#328]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.bilibili.com/

### 什么问题 What happens?
不会每次都出现，出现几率很小，但是确实存在

### 附注(列出有问题的规则,截图,建议等) Other details:
www.bilibili.com#?#.feed-card:has(.bili-video-card__info--ad)
![image](https://user-images.githubusercontent.com/69903376/233819950-526f0406-0297-4ef7-8f86-bf282f0c914c.png)

**Comment by cjx82630** [comment]
不影响阅读, 不处理
