### ISSUE TITLE
对“百度搜索移动端导航栏被误屏蔽”的修正

### ISSUE THREAD

**Issue by fxzxmicah** [easylist/easylistchina#330]
@cjx82630 你好，抱歉打扰，但是经过检查，导航栏并没有被屏蔽，只是由于字体为白色而背景被屏蔽导致白色的字体在白色的背景下没有显示出来。所以希望能够撤销这个commit。抱歉。

_Originally posted by @fxzxmicah in https://github.com/easylist/easylistchina/issues/320#issuecomment-1528789000_

**Comment by cjx82630** [comment]
目前没什么问题.

**Comment by fxzxmicah** [comment]
@cjx82630 我的意思是说我原来提的issue有问题，或者说，我就不应该提。
