### ISSUE TITLE
百度翻译

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#337]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://fanyi.baidu.com/#en/zh/crap`

### 什么问题 What happens?

手机访问页面底部有广告

### 附注(列出有问题的规则,截图,建议等) Other details:

![image](https://github.com/easylist/easylistchina/assets/81752398/8b6bac0c-4f97-4571-9122-24de53c90ac3)

```adblock
||fanyi.baidu.com/wise/afd
```

**Comment by cjx82630** [comment]
1307ac5003a281d21b2b4fe79212bb97315d0b60
