### ISSUE TITLE
baidu.com

### ISSUE THREAD

**Issue by asdfj2381k** [easylist/easylistchina#338]
### 列出存在问题的网址 List the website(s) you're having issues:
baidu.com

### 什么问题 What happens?
有广告

### 列出你启用的列表 List Subscriptions you're using:
easylistchina

### 你的设置 Your settings
- 系统/版本 OS/version:  iOS 16.4
- 浏览器/版本 Browser/version:  safari 
- 过滤工具/版本 Adblock Extension/version: 
- adguard

### 附注(列出有问题的规则,截图,建议等) Other details:
请看截图

**Comment by cjx82630** [comment]
1801544a1c914c0d506968aa2adc20d129af7a37
