### ISSUE TITLE
List breaking wap.gamersky.com for iOS and macOS Safari

### ISSUE THREAD

**Issue by eporubin** [easylist/easylistchina#339]
### 列出存在问题的网址 List the website(s) you're having issues:
wap.gamersky.com
https://wap.gamersky.com/gl/Content-1598632.html 

### 什么问题 What happens?
If you have enabled Ad Block Plus for safari on macOS or iOS for with Safari if you try to open any subpage of from this domain the page cant be loaded it says it was blocked by a content blocker: 
![image](https://github.com/easylist/easylistchina/assets/33602691/eed44df9-8c15-4db0-acd8-51f6a8b4dca4)

This filter seems to be the fault could you please remove it: 
`||gamersky.com^*.htm$subdocument`
Added with this commit: https://github.com/easylist/easylistchina/commit/87deadde7ce9a37260f941d2e82a33474370e691

### 列出你启用的列表 List Subscriptions you're using:
EasyList China + Easy List
Allow Acceptable Ads

### 你的设置 Your settings
- 系统/版本 OS/version: macOS Ventura 13.3.1
- 浏览器/版本 Browser/version: Safari Version 16.4 (18615.1.26.110.1)
- 过滤工具/版本 Adblock Extension/version: Adblock Plus for safari 2.2.6

### 附注(列出有问题的规则,截图,建议等) Other details:
Same issue is reproducible on mobile too.

**Comment by cjx82630** [comment]
05585b08d4ffd2a6a634aa09d1c4c2bd92b74021
