### ISSUE TITLE
Steam图片被误屏蔽

### ISSUE THREAD

**Issue by huijiyun** [easylist/easylistchina#34]
[](url)
![搜狗截图20210627211437](https://user-images.githubusercontent.com/12100004/123545850-c545a080-d78c-11eb-9087-a63966035ac0.jpg)
![搜狗截图20210627211448](https://user-images.githubusercontent.com/12100004/123545851-c70f6400-d78c-11eb-9613-2a3c9aaa6fa2.jpg)

**Comment by cjx82630** [comment]
更新规则, easylist     https://github.com/easylist/easylist/commit/9a35decd7429737af9c814bf16cf30caed8f9399
