### ISSUE TITLE
22.com

### ISSUE THREAD

**Issue by Sonic5435325** [easylist/easylistchina#340]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://22.com/`

### 什么问题 What happens?
Advertisement
`22.com##.advertising`
![Screenshot from 2023-06-21 01-03-13](https://github.com/easylist/easylistchina/assets/89158249/0c50ff6d-ed23-42a8-8a05-a6275dd1e69b)

### 列出你启用的列表 List Subscriptions you're using:
EasyList
EasyList China

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version:

**Comment by cjx82630** [comment]
Self-promotion
