### ISSUE TITLE
tacool.com

### ISSUE THREAD

**Issue by 2xiuno** [easylist/easylistchina#342]
### 列出存在问题的网址 List the website(s) you're having issues:
tacool.com

### 什么问题 What happens?

这个域名知识用来做工单系统api的，为什么会在屏蔽列表里，导致很多用户工单提交不了。

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version:

**Comment by CJ22TIAN** [comment]
tacool.com 是我们公司的业务安全验证和提交的对接域名，其中包含：工单系统的API，CDN系统的验证接口，CDN系统的JS和验证图片、验证码等信息输出，很多的用户网站在使用我们的CDN，很多的网站都可能引入的我们这个域名下的资源，这个域名绝对不包含任何广告和违法内容，如果被拦截，可能导致很多网站无法正常的访问，请核实验证并从easylist中删除，谢谢。

**Comment by cjx82630** [comment]
b6277b25a23512fb562a8cf840d6c64fb30ef778
