### ISSUE TITLE
m.hkgolden.com , lihkg.com

### ISSUE THREAD

**Issue by hspzfsc** [easylist/easylistchina#344]
### 列出存在问题的网址 List the website(s) you're having issues:
https://m.hkgolden.com/thread/7709038/page/1
https://lihkg.com/thread/3431138/page/1
### 什么问题 What happens?
廣告的殘留空位未移除

### 列出你启用的列表 List Subscriptions you're using:
uBlock filters 
EasyList
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
EasyList – Annoyances
uBlock filters – Annoyances
Bypass Paywalls Clean filter
EasyList China
Fanboy's Anti-thirdparty Fonts

### 你的设置 Your settings
- 系统/版本 OS/version: Android 10
- 浏览器/版本 Browser/version: Kiwi Browser 112.0.5615.137
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.50.0

### 附注(列出有问题的规则,截图,建议等) Other details:
![20230701_181809](https://github.com/easylist/easylistchina/assets/138294540/5d3cc951-e6c4-4c20-939f-75b5ce103659)
![20230701_183251](https://github.com/easylist/easylistchina/assets/138294540/14cf0bed-cbd7-47b3-85aa-312dd3824bd7)

**Comment by cjx82630** [comment]
容易造成误拦, 不处理
