### ISSUE TITLE
Bilibili搜索结果广告

### ISSUE THREAD

**Issue by shikibu-z** [easylist/easylistchina#348]
### 列出存在问题的网址 List the website(s) you're having issues:
https://search.bilibili.com/all?keyword=%E5%8D%A1%E8%8A%99%E5%8D%A1

### 什么问题 What happens?
广告未被移除

### 列出你启用的列表 List Subscriptions you're using:
- ABP filters
- EasyList China + EasyList
- EasyPrivacy
- Fanboy's Notifications Blocking List
- Fanboy's Social Blocking List

### 你的设置 Your settings
- 系统/版本 OS/version: macOS Ventura 13.5
- 浏览器/版本 Browser/version: Chrome 115.0.5790.170 正式版本 arm64
- 过滤工具/版本 Adblock Extension/version: Adblock Plus 3.18.1

### 附注(列出有问题的规则,截图,建议等) Other details:
搜索结果中广告未被移除
![截屏2023-08-09 21 49 49](https://github.com/easylist/easylistchina/assets/74883013/17bd8d43-0bc5-4970-8610-c467756f31f8)
似乎现在新的`data-target-url`一项变成了`https://www.bilibili.com/video/BV1Xm4y1H7Kv`和此处不匹配了。上层的tag class也变成了`col_3 ...`。
https://github.com/easylist/easylistchina/blob/72f237cc0d750539dcc17b2e80845cd262ce1aa3/easylistchina.txt#L16185
修改为`bilibili.com##a[href*="cm.bilibili.com"] + .bili-video-card`可以移除广告但是无法消除空白。

**Comment by cjx82630** [comment]
30分钟后更新 c331830d1ab805ad6a40bdbfb1e1735bc11d03ff
Fixed.Please manually update in 30 minutes.
