### ISSUE TITLE
Inactive Domains

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#35]
Inactive domains found by running PyFunceble on whole easylistchina.txt. The 'inactiveness' is mostly attributed to DNS LOOKUP, i.e. no DNS records.

![1](https://user-images.githubusercontent.com/8369201/123577881-29d02200-d7c4-11eb-8707-ab71ee493658.jpg)

0316dieroxiemzfjwmapk.xyz
0323wqpioutyuencsamxsd.xyz
0330vsdgdwer.xyz
0413fsiuhwem.xyz
0420zvnmljgfdsa.xyz
1.201980.com
1.32xp.com
1.hnyouneng.com
1.jeasyui.net
1.rr95.com
1.xuexi.la
1.zou114.com
1.zw3e.com
100.admin5.com
11.golang8.com
11.yiqig.com
1pzskg.cn
1x26q3.cn
2016.bkill.net
21.cizhibaogao.org
215to.cn
282l1.cn
2shol4.cn
3.guidaye.com
3ye924.cn
4ekx.cn
4z5o27.cn
5.douben8.com
5j73de.cn
5jcom.com.cn
5mgurg.cn
5p68n.cn
5q63n.cn
5q68n.cn
5x0f.cn
5zi2.top
5zi3.top
5zi5.top
60cjstatic.wow-classic.com
61.iqiyi.com
6s7v78.cn
7011.stia.cn
7m307.cn
88.yunqishi.net
8byu.cn
8mlb.cn
8yrn.cn
91porri.org
99btgc01.info
9a6wb.cn
9d7in.cn
9uh94c.cn
a.armystar.com
a.baomihua.com
a.duanmeiwen.com
a.duduji.com
a.icdol.com
a.jing55.com
a.qsjiajiao.com
a.thn21.com
a.yuzhainan.com
a1.aichagu.com
a1.gexing.me
a7t89g4a.cn
aa.wenxue6.com
aa.xiangxiangmf.com
abcj.dooccn.com
abds.pingpingw.com
abie11.top
abie12.top
abie13.top
abie14.top
abie15.top
abie16.top
abie17.top
abie18.top
abie25.top
abie9.top
ac1.pingpingw.com
ad-img.diyidan.net
ad.52av.tv
ad.walkgame.com
ad.wurangxian.top
ad1.nownews.com
adm.cnzz.net
adp.cnki.net
adsclick.yx.js.cn
afp.chinanews.com
afp.wasu.cn
afpcreative.wasu.cn
aifei.info
ajkdg3.xyz
amensh.cn
amghmej.cn
ams.fx678.com
apptry.easylife.tw
aqvnurq.cn
askspsl.cn
aswlx.cn
atm.youku.com
aty.sohu.com
avbaike.org
awqsaged.cn
b.kouke5.com
b1.91jucai.com
b7sw62.pingshu8.xyz
b83pmp.cn
baidu.bxwx3.org
baidu1.codejie.net
baidujs.cnys.com
bbs.52life.cc
bbs.hotavxxx.com
bd.ershenghuo.com
bd1.jinbaozy.com
bd1.ningboseo0574.com
bd100.010lm.com
bdad.gaotie.net
bdasd.chinabig.com.cn
bdasd.wmxa.cn
bdcode.35d1.com
bdjj.makepolo.net
bei7.clewx.com
bfbb.xyz
bgcse.cn
bp.blogspot.com
bpdffh.cn
brand.sogou.com
bsjgqhe.cn
buy.sina.com.tw
bzbsecs.cn
c.mnjkw.cn
c1.4qx.net
c6.friok.com
cahdfzg.cn
cdn-t.xyz
cdn1.tvzhe.com
ceyiuy.com
chinaqirun.cn
chinataxservice.cn
cj1.256.cc
ckjyck.qxs.la
cnzz.com.so
coyvzui.cn
cpm.cm.kankan.com
cpms.cc
cpro.xixiliya.cn
css.juqingba.cn
cxy88.friok.com
d.ab126.com
d1.zhuangxiu6.com
d36gyu.cn
d8ekco.com
da.mgtv.com
dai.siyuetian.net
daima.ijq.tv
data.waptime.cn
daylskg.cn
dehua.ixinfan.com
deliver.ifeng.com
df666.pzhttaax.cn
df888.eastday.com
dilqdiw.cn
dlsdkw.cn
dlswzw.cn
dm.51okc.com
dm.66qw.net
dm.huochepiao.com
dm.pw0.cn
dm.riji.cn
dm.wenshenxiu.com
dmr.cnhoney.com
dodomo.info
down.admin5.com
drmcmm.baidu.com
duiwai.baidu.com
duwowvo.cn
e.changyan.sohu.com
e.yycqc.com
ecuwa.cn
ee.shixunwang.net
egjq.com.cn
enq5ur.cn
epcqyac.cn
ez2kyh.cn
farm-cn.plista.com
fcgcjw.cn
ff.guidaye.com
ffg34fg.877zw.com
fkm2wv.cn
fragment.firefoxchina.cn
frjxdv.cn
ftchinese.com.sz-dns.net
fun.ynet.com
fw.zhuaji.org
fxfvttu.cn
g.3lian.com
g1psz5.cn
g8waw1.cn
gadhx.cn
game.466.com
game.macx.cn
games.ifeng.com
gcctqal.cn
gg.4kdy.net
gg.getbs.com
gg.gsdlcn.com
gg.gw032.com
gg.kugou.com
gg1.mengchongzu.com
ggg.zj.com
ggsgww.cn
gmuqa.cn
go.gotourl.xyz
goods.tudou.com
goto.www.iciba.com
guess.h.qhimg.com
hao.360hyzj.com
hdc.maxli.cn
hdvwm3.cn
hhjkl.cc
hi.xiunm.com
hiad.vmall.com
houyi.baofeng.net
hp0hnj.cn
hrcmzp.cn
hsyjxzl.cn
html.350.com
hu.xbhy.com
huayangli.cn
hudxqjg.cn
hvie6u.cn
hxbt.alading123.com
hz.shouyoutv.com
iads.xinmin.cn
ii1.chajiaotong.com
img.263y.com
img.meipic.net
img.sex169.info
img2.126.net
ip.hivps.xyz
ipdxwtn.cn
ipeen.com.tw
ipqxibd.cn
iwan.baidu.com
iwanad.baidu.com
iwwacgx.cn
j.avz4.com
j.imdb.cn
jiaoben.eastday.com
jioder3e.cn
jkgnplk.cn
jqhevyf.cn
js.45bubu.com
js.bju888.com
js.jianbihuadq.com
js.kt250.com
jss.tvzhe.com
jssumei.cn
jsvv587.com
jvyigg.biqugeq.com
jvyigg.zbzw.la
jxad.jx163.com
jxwef0.cn
k1.wanwenwan.cn
kan5.xyz
kanjuba.me
kfi8.com
kfuih.cn
kunloveyu.cn
la61d.cn
labuladong.github.io
lalaxit.cn
lfcepgb.cn
lianjie.phpwind.com
ll.gxsky.com
llffaev.cn
lm.35.com
lm1.wzpcw.com
lmdknj.vbiquge.com
log.interest.mix.sina.com.cn
lq0s3c.cn
luolidao.vip
lv.myapks.com
lyz.radio366.com
m.lecai.com
m.nownews.com
m1.100how.com
m2.lelemh.com
mall.xinkuaituan.com
maxfull.info
mcfuns.com.tw
meoqbhw.cn
miniye.xjts.cn
mkaqh.cn
mx.loubiqu.com
n8n7.me
news.tagtoo.co
nlqnmkn.cn
nyaa.pt
o.jy135.com
o5ikm6.cn
oa-panther.data.aliyun.com
oikqfwv.cn
oiwjcsh001.top
oiwjcsh010.top
oiwjcsh011.top
oiwjcsh012.top
oiwjcsh013.top
oiwjcsh015.top
ol6nhf.cn
olc0.cn
orvibum.cn
oxxvideos.xyz
p.7060.la
p.ynb2dca.com
p0pm5z.cn
p4p.sina.com.cn
pb.shuxigua.com
pic.fengniao.com
pic.gunqiu.com
pics.wanlibo.com
pkk1.zuimeiniwo.com
pu0glv.cn
publish.ad.youth.cn
pzvlnh.cn
q38.xyz
q671e.cn
qaqact.cn
qd.x4399.com
qkykxrm.cn
qnpov.cn
qubilou.com
qwfknhc.cn
qyhwqie.cn
qyule.fun
rcynoe.cn
resource.baomihua.com
rm66.me
rxconkz.cn
s1-a4.ifvod.tv
s1.qiqutt.com
sbbd1.qulishi.com
sbpb1.qulishi.com
shenglonghg.net
shili.downxia.com
sjy-stone.com.cn
skads.gxsky.com
smf82.cn
spcode.baidu.com
static.jiaquyi.com
sv7oqa.cn
syrstrq.cn
taobaocoupon.cn
tiaoweiyou.cn
tt.biquge.la
tt123.eastday.com
tvbyb04.cn
two.game.tw
twodogegg.cn
ucvqmvg.cn
up.hiao.com
uxnycjr.cn
v1.taksh.cn
vf5yb4.cn
voterlin.cn
vv1.pyhfxdm.cn
vvv.ieduw.com
wew.dushiwenxue.net
ws.wenshenxiu.com
wtnjupl.cn
wuliao.chzsport.cn
wuliao.juqingba.cn
wvfgiio.cn
xc.gouchezj.com
xc.mydrivers.com
xcf-bd-js.chuimg.com
xindelin.cn
xingqu.baidu.com
xingyao.doubiy.com
xinyijiasc.cn
xn--2qu92fhtx4ff.icu
xn--2qu92fhtx4ff.ink
xn--2qu92fhtx4ff.ren
xn--2qux23c9ziyrq.icu
xn--2qux23c9ziyrq.ink
xn--2qux23c9ziyrq.video
xn--2quz8f01ak10c.shop
xnmcmnt.cn
xswfkco.cn
xuyssur.cn
yizhijin.cn
youxi.kugou.com
ywqum.cn
ywxtmox.cn
yx1.managershare.com
z5of63.cn
zg.mmyuer.com
zgdfvih.cn
zhongyi.ifeng.com
zoepb.cn
zt.chuanke.com
zuoye.baidu.com

**Comment by cjx82630** [comment]
Removed.
