### ISSUE TITLE
please remove our domain, It has affected our normal business.

### ISSUE THREAD

**Issue by sky-gg** [easylist/easylistchina#351]
https://github.com/easylist/easylistchina/blob/2038fa30d1eeb7381afa4263a3105843ddaef47e/easylistchina.txt#L4283

**Comment by sky-gg** [comment]
https://chat.heytap.com/chat/h5/v2/index.html?sysnum=9f06d616a05a43a9a50421f5f0982e4d&channelid=64

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. ca78af6feeab53642b4a2bde7a5ec739e2061560
