### ISSUE TITLE
fffmo.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#352]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://www.fffmo.com/926/`

### 什么问题 What happens?

网站检测到广告拦截，弹窗影响浏览

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. bf14ed0a874d8ce6dddb4064e4c10e35591b865d
