### ISSUE TITLE
知乎侧栏广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#353]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://www.zhihu.com/question/620282717`

### 什么问题 What happens?

右侧广告卡片

### 附注(列出有问题的规则,截图,建议等) Other details:

![image](https://github.com/easylist/easylistchina/assets/81752398/adc2e770-ceda-47e2-8cd6-6297554fbd74)

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes. 5b2c203332bf478e448e829625c4b2b0bab752eb
