### ISSUE TITLE
A:`https://sumiutravel.com/`

### ISSUE THREAD

**Issue by eporubin** [easylist/easylistchina#354]
### 列出存在问题的网址 List the website(s) you're having issues:

https://sumiutravel.com/
### 什么问题 What happens?
Hi there seems to be some redirecting ads on top of the domain (in the middle in black) 
![image](https://github.com/easylist/easylistchina/assets/33602691/d42faa76-a2ca-4d52-947d-3be63328996c)

### 列出你启用的列表 List Subscriptions you're using:
ABP filters
EasyList China+EasyList

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:

This filter seems to work for me: `sumiutravel.com##.elementor-widget-container>iframe`

**Comment by cjx82630** [comment]
b47f35b187681d30fc4ceaaa46b55b5db2da1121
