### ISSUE TITLE
规则覆盖范围太大了

### ISSUE THREAD

**Issue by maxzhang666** [easylist/easylistchina#362]
### 列出存在问题的网址 List the website(s) you're having issues:
*.wandhi.com

### 什么问题 What happens?
tv.wandhi.com 域名下的广告规则请直接写到二级域名
现在写到根域把其他站点也影响了
```table```这种class过于广泛了

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version:

**Comment by cjx82630** [comment]
如有误拦, 请反馈

**Comment by maxzhang666** [comment]
啊？我不是在反馈误拦么？？
