### ISSUE TITLE
ping.chinaz.com

### ISSUE THREAD

**Issue by Karmylr** [easylist/easylistchina#364]
### 列出存在问题的网址 List the website(s) you're having issues:
https://ping.chinaz.com/223.5.5.5

### 什么问题 What happens?
把鼠标指针移到地图里的东部地区上，出现的框会闪烁

### 列出你启用的列表 List Subscriptions you're using:
Easylist
Easyprivacy
Easylist China

是`||a2put.chinaz.com^`导致的

**Comment by cjx82630** [comment]
不能重现
