### ISSUE TITLE
cool3c.com

### ISSUE THREAD

**Issue by TotalImportance8529** [easylist/easylistchina#367]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.cool3c.com/article/202904`

### 什么问题 What happens?
廣告及殘留物

### 列出你启用的列表 List Subscriptions you're using:
``` yaml 
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 199023
 cosmetic: 124973
 scriptlet: 25749
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  CHN-0: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22528-12, 5m
  adguard-spyware-url: 1306-5, 5m
  block-lan: 54-0, 5m
  curben-phishing: 76454-20, 5m
  easylist-annoyances: 4164-32, 5m
  easylist-chat: 148-0, 5m
  easylist-newsletters: 6624-15, 5m
  easylist-notifications: 2870-82, 5m
  fanboy-cookiemonster: 48858-223, 5m
  fanboy-social: 16184-13, 5m
  ublock-annoyances: 5766-81, 5m
  ublock-cookies-easylist: 490-490, 5m
 default:
  easylist: 75139-21, 5m
  easyprivacy: 32843-163, 5m
  ublock-badware: 7430-143, 5m
  ublock-filters: 35152-179, 5m
  ublock-privacy: 653-90, 5m
  ublock-quick-fixes: 137-86, 5m
  ublock-unbreak: 2133-36, 5m
  urlhaus-1: 12585-0, 5m
filterset (user): [array of 13 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoCommentFilterTemplate: none
supportStats:
 allReadyAfter: 2055 ms (selfie)
 maxAssetCacheWait: 1428 ms
```

### 你的设置 Your settings
- 系统/版本 OS/version: Android 10; Build/QP1A.190711.020
- 浏览器/版本 Browser/version: Kiwi Browser 116.0.5845.240
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.52.2 

### 附注(列出有问题的规则,截图,建议等) Other details:
![Screenshot_20231107-194725_Kiwi Browser](https://github.com/community/community/assets/146954135/3ae9b011-fa2b-458e-b934-9af54f700d2d)
![Screenshot_20231107-194804_Kiwi Browser](https://github.com/community/community/assets/146954135/63f1ba65-6344-4e0a-8405-3a273be5eed6)
![Screenshot_20231107-194827_Kiwi Browser](https://github.com/community/community/assets/146954135/35a6b1f2-12ab-49ff-bea6-0b3a733ffee3)

**Comment by cjx82630** [comment]
db63f0998fd2d6e3ce0c294e88901bdc9a6ba841
