### ISSUE TITLE
log-reporter.js 白名单

### ISSUE THREAD

**Issue by Hill-98** [easylist/easylistchina#369]
`@@/log/report/*$script,domain=bilibili.com`

我注意到 EasyList China 有个针对 bilibili.com 的 log-report 的白名单规则，能解释一下这是为什么吗？

**Comment by cjx82630** [comment]
拦截脚本导致一些奇怪的问题.

**Comment by sncix** [comment]
这个问题我也比较好奇，因为我自己一直是屏蔽 log-reporter.js 的，没有因此遇到过问题。于是我调查了一下，根据 git blame 的结果，最初是在 d630f12d3133de03f340f1c34be45a2ea6f723b5 这个 commit 引入了 `@@||hdslb.com/bfs/seed/log/report/log-reporter.js$domain=message.bilibili.com`；然后 109a7787593ce05add53b3a33257b1cc9dae3a03 扩大了白名单范围，去掉了 `domain=message.bilibili.com` 的限制；最后 b1eaa2fc058c29792631f39779423d224a65059b 把白名单重写为 `@@/log/report/*$script,domain=bilibili.com`。

因为 commit message 比较简略，只能猜测这条规则和哪些页面有关，不知道有没有谁了解具体是哪些问题。

**Comment by cjx82630** [comment]
曾经存在的问题, 比如[这个页面](https://space.bilibili.com/730732#!/index), 当点"查看更多"时,不能跳转.
