### ISSUE TITLE
Taiwanese easycard ads

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylistchina#37]
```
https://epkaw.easycard.com.tw/resource/advertisement/b740cf6b-427d-4617-8295-5364220afade.jpg

||epkaw.easycard.com.tw/resource/advertisement^
```

https://github.com/easylist/easylist/issues/8354

**Comment by cjx82630** [comment]
Please provide the URL where the ads exists.

**Comment by c2xusnpq6** [comment]
https://play.google.com/store/apps/details?id=com.easycard.wallet

**Comment by cjx82630** [comment]
Please provide the website URL that I can reach.

**Comment by c2xusnpq6** [comment]
https://apkpure.com/p/com.easycard.wallet

https://www.easycard.com.tw/

**Comment by c2xusnpq6** [comment]
你不是用android的???....

**Comment by cjx82630** [comment]
ABP处理网页广告, 不处理APP内广告
