### ISSUE TITLE
mala.cn

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#370]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://mala.cn/t/16559083`

### 什么问题 What happens?

手机访问有广告

### 附注(列出有问题的规则,截图,建议等) Other details:

![image](https://github.com/easylist/easylistchina/assets/81752398/171921ff-540d-45d7-9f56-445d3a1adcfd)

```adblock
||adx.mala.cn^
```

**Comment by cjx82630** [comment]
3311f2aba62bbdad310c9e6355b4450d12fd0a3e
