### ISSUE TITLE
m.baike.so.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#371]
### 列出存在问题的网址 List the website(s) you're having issues:

`https://m.baike.so.com/doc/3088580-3255451.html`

### 什么问题 What happens?

页尾广告

### 附注(列出有问题的规则,截图,建议等) Other details:

![image](https://github.com/easylist/easylistchina/assets/81752398/7293f0f4-ca12-47c8-a818-df93dde6ca0a)

**Comment by cjx82630** [comment]
7b9d2cb5863f560939441e8697904c6c978c40da
