### ISSUE TITLE
hkjunkcall.com, taiwancall.com, junk-call.com

### ISSUE THREAD

**Issue by hamburgerguitar** [easylist/easylistchina#373]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.junk-call.com`
`https://hkjunkcall.com/`
`https://taiwancall.com/`

### 什么问题 What happens?
廣告、空位

### 列出你启用的列表 List Subscriptions you're using:
Brave 預設列表 ＋ Fanboy's, uBlock Annoyances

### 你的设置 Your settings
- 系统/版本 OS/version: Android 10; Build/QP1A.190711.020
- 浏览器/版本 Browser/version: Brave 1.61.109, Chromium 120.0.6099.144
- 过滤工具/版本 Adblock Extension/version: Brave 內置 adblocker

**Comment by cjx82630** [comment]
5465e801bd415724b313cff58964b0233ef6b4b1
