### ISSUE TITLE
doubiuser.github.io

### ISSUE THREAD

**Issue by hamburgerguitar** [easylist/easylistchina#375]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://doubiuser.github.io/3--didfb.html`

### 什么问题 What happens?
廣告

### 列出你启用的列表 List Subscriptions you're using:
AdGuard Mobile Ads
AdGuard URL Tracking
Fanboy's Anti-Facebook List
Fanboy's Annoyances
AdGuard Chinese
Brave 內置列表
uBlock Annoyances

### 你的设置 Your settings
- 系统/版本 OS/version: Android 10; Build/QP1A.190711.020
- 浏览器/版本 Browser/version: Brave 1.61.114, Chromium 120.0.6099.199
- 过滤工具/版本 Adblock Extension/version: Brave Shields

### 附注(列出有问题的规则,截图,建议等) Other details:
[截圖](https://cdn.adguard.info/sitereports/70uh3u2z77cw0oo48ws0sww00cg0kwskl8lvbno4lc.jpg?nc=1)

**Comment by cjx82630** [comment]
9d0ef26b62763b502f8242c29f72cc9b9c05085a
