### ISSUE TITLE
腾讯视频加载视频的地址被屏蔽

### ISSUE THREAD

**Issue by Hill-98** [easylist/easylistchina#376]
### 列出存在问题的网址 List the website(s) you're having issues:

https://v.qq.com/x/cover/mzc00200aoe8a04.html

### 什么问题 What happens?

腾讯视频使用 `ltscsy.qq.com` 加载视频流（如以下截图所示），虽然它有好几个后备地址，但是这在配合某些客户端使用时会导致一些问题，比如 AdGurad 客户端。

![图片](https://github.com/easylist/easylistchina/assets/25147395/c34e5502-4963-4e7f-97da-72e65ad0c8b8)

所以清删除以下规则：
```
||lts*.qq.com^*.ts?index=$media,rewrite=abp-resource:blank-mp3,domain=qq.com
```

**Comment by cjx82630** [comment]
b5c6477e99c8d274b9eeafb776679592b8115c8d
