### ISSUE TITLE
微博转发内容误拦截

### ISSUE THREAD

**Issue by JimJokes** [easylist/easylistchina#377]
### 列出存在问题的网址 List the website(s) you're having issues:
weibo.com

### 什么问题 What happens?
微博转发的内容被拦截了

### 列出你启用的列表 List Subscriptions you're using:
ABP filters
Adblock Warning Removal List
EasyList
EasyList China+EasyList (compliance)
EasyPrivacy
Fanboy's Notifications Blocking List
Fanboy's Social Blocking List
Japanese Filters+EasyList
Allow nonintrusive advertising without third-party tracking

### 你的设置 Your settings
- 系统/版本 OS/version: win64
- 浏览器/版本 Browser/version: Chrome/版本 120.0.6099.224（正式版本） （64 位）
- 过滤工具/版本 Adblock Extension/version: Adblock Plus

### 附注(列出有问题的规则,截图,建议等) Other details:
关闭拦截：
![image](https://github.com/easylist/easylistchina/assets/12324468/7243b212-2647-4b37-943d-af47f7eecf4c)

开启拦截：
![image](https://github.com/easylist/easylistchina/assets/12324468/fef1e501-8ba4-4edf-a4f4-058d7956b20b)

**Comment by cjx82630** [comment]
社交按钮列表的原因, 你更新中文规则即可.
