### ISSUE TITLE
openrice.com

### ISSUE THREAD

**Issue by randompasser** [easylist/easylistchina#379]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www1.openrice.com/zh/hongkong/restaurants?whatwhere=%E8%A7%80%E5%A1%98&tabIndex=0

### 什么问题 What happens?
搜尋結果廣告卡片
<img width="1448" alt="Screenshot 2024-01-23 at 23 57 11" src="https://github.com/easylist/easylistchina/assets/33059426/03a386f4-f9c9-4626-85df-90b75fc421e8">

### 你的设置 Your settings
- 系统/版本 OS/version: macOS 14.3
- 浏览器/版本 Browser/version: Firefox 121.0.1
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.55.0

### 附注(列出有问题的规则,截图,建议等) Other details:
`##.poi-list-cell-desktop-container.poi-list-cell:has(.sponsored-info)`可以移除

**Comment by cjx82630** [comment]
属于站内链接, 不适宜移除.
