### ISSUE TITLE
hosts.txt

### ISSUE THREAD

**Issue by c2xusnpq6** [easylist/easylistchina#38]
搞一个hosts版本...即只有domain的版本可以么 谢

**Comment by c2xusnpq6** [comment]
我想放在adguard home使用

**Comment by c2xusnpq6** [comment]
「easylist china + easylist」的hosts.txt

**Comment by c2xusnpq6** [comment]
easylist直接提取domain的版本
还有一个是`$third-party`的也封锁的版本

**Comment by cjx82630** [comment]
请访问adguard home项目, 应该有相应的方案.
