### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by qinshao1** [easylist/easylistchina#380]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.tongjiniao.com/

### 什么问题 What happens?
错误拦截官网样式为广告，导致官网无法正常展示

### 列出你启用的列表 List Subscriptions you're using:
EasyList China

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10/22H2
- 浏览器/版本 Browser/version:  Google Chrome/121.0.6167.86
- 过滤工具/版本 Adblock Extension/version: AdGuarD/4.2.241

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://github.com/easylist/easylistchina/assets/71258607/a8bd46e1-bea4-477e-95c6-37abc5b3d89b)
![image](https://github.com/easylist/easylistchina/assets/71258607/13284c8f-2c51-4c86-bc6c-64bc49b615e8)

此域名中不符合广告标准，建议去除处EsayListChina中

**Comment by cjx82630** [comment]
8dff29474cabafc1cfcb38af133b3564e29262e9
