### ISSUE TITLE
original design templates

### ISSUE THREAD

**Issue by Pankos1** [easylist/easylistchina#381]
### 列出存在问题的网址 List the website(s) you're having issues:
www.tj1736.com

### 什么问题 What happens?
1736网站(网站地址: www.tj1736.com）盗用统计鸟官网设计样式，盗用统计鸟官网全局原创设计模板，设计的图标，文案，给大多数用户认为，该网站与统计鸟属同一家产品，误导用户，侵犯统计鸟的创作成果，给统计鸟品牌形象带来不可估量的影响，统计鸟官网地址：wwwtonglinlao.com

### 列出你启用的列表 List Subscriptions you're using:
EasyListChina 

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10/22H2
- 浏览器/版本 Browser/version: Microsoft Edge /121.0.2277.83
- 过滤工具/版本 Adblock Extension/version: AdGuard /4.2.241

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://github.com/easylist/easylistchina/assets/107384117/5f3fb569-2b65-49f5-a21e-59db6c3b9254)
![image](https://github.com/easylist/easylistchina/assets/107384117/14d03be9-ab5f-4a63-8811-cae9eaac8b1a)

**Comment by cjx82630** [comment]
在哪些网站会出现这域名?

**Comment by Pankos1** [comment]
就这个[www.tj1736.com](https://tj1736.com/)

**Comment by cjx82630** [comment]
在哪些网站加载的脚本文件会包含这个域名?
