### ISSUE TITLE
Bootstrap 的 btn-outline-primary 类元素易引起误过滤

### ISSUE THREAD

**Issue by choking-chips** [easylist/easylistchina#382]
### 列出存在问题的网址 List the website(s) you're having issues:
自建网页

### 什么问题 What happens?
`<a class="btn btn-outline-primary" href="...">...</a>`
若href的链接中任何层级的域名以cc开头，该元素即被隐藏，容易引起误过滤。

### 列出你启用的列表 List Subscriptions you're using:
EasyList China

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 11
- 浏览器/版本 Browser/version: Chrome 120
- 过滤工具/版本 Adblock Extension/version: AdGuard/4.3.13

### 附注(列出有问题的规则,截图,建议等) Other details:
位于 [L17124](https://github.com/easylist/easylistchina/blob/master/easylistchina.txt#L17124)，内容为`##.btn-outline-primary[href*=".cc"]`。

**Comment by cjx82630** [comment]
16565661cfec846dd12ca6e599cd0f31e0919e1d
