### ISSUE TITLE
qidian.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#39]
您好！
链接地址：https://m.qidian.com/book/1982186
![Screenshot_2021-07-23-00-36-15-123_org mozilla firefox](https://user-images.githubusercontent.com/66902050/126675785-4935c09e-bcce-423f-b6dd-f44f21520bb2.jpg)
谢谢！

**Comment by cjx82630** [comment]
订阅easylist

**Comment by shenzhiming88** [comment]
挺奇怪的……我手机上订阅了easylist，仍然有这个广告，但是电脑上就没有……
