### ISSUE TITLE
遺漏封鎖的廣告與白塊

### ISSUE THREAD

**Issue by a77841s** [easylist/easylistchina#390]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.pixnet.net
以及
https://kwytlife2019.net/blog/post/150430192-亞瑟蘭印度餐廳_秒飛印度吃！台北印度料理
還有
https://www.sogi.com.tw/articles/vivo_v30_pro_5g/6261581

### 什么问题 What happens?

許多未封鎖的廣告與大量白塊

### 列出你启用的列表 List Subscriptions you're using:
Easylist China
Easylist

### 你的设置 Your settings
- 系统/版本 OS/version: Android 
- 浏览器/版本 Browser/version: Brave
- 过滤工具/版本 Adblock Extension/version:

**Comment by cjx82630** [comment]
请截图. Please provide some screenshots.
