### ISSUE TITLE
`topic.expreview.com`

### ISSUE THREAD

**Issue by yueisme** [easylist/easylistchina#391]
### 列出存在问题的网址 List the website(s) you're having issues:
https://topic.expreview.com/GPU/

### 什么问题 What happens?
无限自动刷新，下列过滤器都会触发

### 列出你启用的列表 List Subscriptions you're using:

- https://github.com/easylist/easylistchina
- https://github.com/xinggsf/Adblock-Plus-Rule/

### 你的设置 Your settings
- 系统/版本 OS/version: windows 11 23h2
- 浏览器/版本 Browser/version: chrome 125
- 过滤工具/版本 Adblock Extension/version:  adguard 7.17.1

### 附注(列出有问题的规则,截图,建议等) Other details:
none

**Comment by cjx82630** [comment]
ABP不能重现. 可能是adg的问题. Cannot reproduce.
