### ISSUE TITLE
THBWiki误杀

### ISSUE THREAD

**Issue by Whuihuan** [easylist/easylistchina#394]
### 列出存在问题的网址 List the website(s) you're having issues:
thwiki.cc

### 什么问题 What happens?
网站的首页轮播被误杀

### 列出你启用的列表 List Subscriptions you're using:
easylistchina

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:
#199 
两年前反馈过一次，这个轮播用途是用于东方官作正版贩售渠道宣传、ZUN生日庆祝、东方project活动相关推荐、本站特定节日活动宣传等用途，除了贩售官作外含引流淘宝店之外，并没有其他广告性质的用途。这样突然屏蔽我们很困扰= =，我们也不想像其他网站一样做对抗，这样没有意义

**Comment by cjx82630** [comment]
9f59e437e8d47a1a4311f7f5182be7e4a6aa487d
