### ISSUE TITLE
www.zhihu.com

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#398]
### 列出存在问题的网址 List the website(s) you're having issues:
`https://www.zhihu.com/tardis/baidu/qus/661457792`

### 什么问题 What happens?
页面底部，百度网盟广告

### 附注(列出有问题的规则,截图,建议等) Other details:
`||udd1i5.zhihu.com^`

**Comment by cjx82630** [comment]
34c513cf4109fc19926db53a0ecffd07d6a89b1d
