### ISSUE TITLE
trafficmanager.net

### ISSUE THREAD

**Issue by 6r33z3** [easylist/easylistchina#399]
### 列出存在问题的网址 List the website(s) you're having issues:

https://github.com/easylist/easylistchina/blob/da56854b4afe39d5236b9c9ccdaa1b3bcca01763/easylistchina.txt#L1728

### 什么问题 What happens?

因Adguard Chinese filter继承了部分Easylist China的规则，继而追溯到上条规则的上游Easylist China。

`trafficmanager.net`是Azure的架构之一，如果屏蔽则会导致整体Microsoft服务无法访问，包括Edge，VSCode，Microsoft 365等。

针对此域名，建议只屏蔽个别子域名，例如：

https://github.com/AdguardTeam/AdguardFilters/blob/af84c7cbe9aa28ebb0c7630db07df230874b9d38/TurkishFilter/sections/specific.txt#L3766

https://github.com/AdguardTeam/AdguardFilters/blob/af84c7cbe9aa28ebb0c7630db07df230874b9d38/SpywareFilter/sections/tracking_servers_firstparty.txt#L772

### 附注(列出有问题的规则,截图,建议等) Other details:

![image](https://github.com/user-attachments/assets/aefcf0f6-e549-4003-bb4a-205f9ecb479c)

**Comment by nd002723** [comment]
补充：login.live.com 也被错误封锁导致我xbox无法登录

**Comment by cjx82630** [comment]
d5a2f9a837c91a11128adfd6769658164b0ddb9e
