### ISSUE TITLE
masuit.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#40]
您好！
链接：https://masuit.com/1251
![image](https://user-images.githubusercontent.com/66902050/126793651-d1ea6564-ee83-4065-840c-1b4bb6dcacf8.png)

**Comment by cjx82630** [comment]
已处理.请30分钟后手动更新(点击ABP图标>齿轮>高级>更新).

**Comment by shenzhiming88** [comment]
> 已处理.请30分钟后手动更新(点击ABP图标>齿轮>高级>更新).

好的，感谢
