### ISSUE TITLE
误杀

### ISSUE THREAD

**Issue by dnddk** [easylist/easylistchina#400]
### 列出存在问题的网址 List the website(s) you're having issues:

chunyuqiufeng.com

### 什么问题 What happens?

公司官网被屏蔽

### 列出你启用的列表 List Subscriptions you're using:

EasyListChina

### 附注(列出有问题的规则,截图,建议等) Other details:

问题规则：
![image](https://github.com/user-attachments/assets/32eb5f27-ef5c-4d89-9dfa-fd6c67fd56d9)

页面样式显示异常：
![37d37085a6beed615c990dca038ef06](https://github.com/user-attachments/assets/553a2ee5-7589-4603-956b-d9df1315469e)

取消过滤后显示正常：
![e31e917a717b46b16eb61c4be435a2b](https://github.com/user-attachments/assets/832259b6-0bed-4657-a460-4d3cb26c2b59)

**Comment by cjx82630** [comment]
c528f1e16f5bfbab25573df8b8cdc4142ab001ac
