### ISSUE TITLE
百度搜索vivo OPPO关键词时会误杀。

### ISSUE THREAD

**Issue by Aloazny** [easylist/easylistchina#401]
### 列出存在问题的网址 List the website(s) you're having issues:

https://www.baidu.com/from=844b/s?word=vivo

### 什么问题 What happens?

百度搜索vivo OPPO关键词时会误杀。

### 列出你启用的列表 List Subscriptions you're using:
[Easylist China](https://easylist-downloads.adblockplus.org/easylistchina.txt)
[Adblock Warning Removal List](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt)
[CJX's Annoyance List](https://fastly.jsdelivr.net/gh/cjx82630/cjxlist/cjx-annoyance.txt)

### 你的设置 Your settings
- 系统/版本 OS/version: Android10
- 浏览器/版本 Browser/version: Xbrowser
- 过滤工具/版本 Adblock Extension/version: 无

### 附注(列出有问题的规则,截图,建议等) Other details:
误杀规则为
```
||ecma.bdimg.com^
||ecmb.bdimg.com^
```
- 截图① ![Screenshot_2024-08-22-09-38-29-135-edit_com xbrowser play](https://github.com/user-attachments/assets/52db980b-8fea-4757-99a5-523381dc5284)
- 截图② ![Screenshot_2024-08-22-09-45-55-655_com mmbox xbrowser](https://github.com/user-attachments/assets/6ab80ed8-2452-467a-a70c-26e26a62cc6c)

**Comment by Aloazny** [comment]
- 误杀图片链接
```
https://ecma.bdimg.com/public01/super_logo/e5bd4faeba4d46888b0d2fc8a5e48e3a.png
```
```
https://ecmb.bdimg.com/tam-ogel/-206110091_-416764012_1200_800.jpg
```

**Comment by cjx82630** [comment]
`||ecma.bdimg.com^`拦截品牌广告,另外可能你列表没有更新.

**Comment by Aloazny** [comment]
> `||ecma.bdimg.com^`拦截品牌广告,另外可能你列表没有更新.

？也就是说您觉得这是个广告，但只拦截了图片，没有做元素规则隐藏？这也太难受了，留几个空白图片在哪看着很难受。
另外那个链接是最新的？下面这两个我都试过了，已经全部更新。

```
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt
```
