### ISSUE TITLE
Bundle - Adservers / Banner ads

### ISSUE THREAD

**Issue by CbumDino** [easylist/easylistchina#404]
### 列出存在问题的网址 List the website(s) you're having issues:
https://nlb-rdc8bd8r5zgcdigffc.cn-beijing.nlb.aliyuncs.com:8283/home?channel=gj-89
https://www.dk95.com/mfdm/65-1-1.html
http://p.fzshor.cn/?channelId=170
https://www.fe-siken.com/s/kakomon/06_haru/
https://css.ybz580.com/ts/ts.html
https://ctzg.yt-laub665.vip/
https://www.danmutv.com/play/vaid/ZcIlbHN27JE2Ej.html
https://w8r7.xyz/rain/a/514004.html?channel=514004&ucid=E4565682&utid=DF3650&key=1
https://movie.ying35.com/movie/4586.html
https://www.jinnanyq.com/yq/163723/198016702.html

https://shp.qpic.cn/collector/1639975930/f0fc31b2-3ed0-48a8-942a-0fba0100f86d/0?i=0 (This should be an adserver itself)

### 什么问题 What happens?
Ad's (adservers and banners) and/or placeholders 
Majority **[NSFW]**

### 列出你启用的列表 List Subscriptions you're using:
EL China
ABP

### 你的设置 Your settings
- 系统/版本 OS/version: MacOS sonoma 14.5
- 浏览器/版本 Browser/version: Chrome 127.0.6533.120
- 过滤工具/版本 Adblock Extension/version:  ABP 4.5.1

**Comment by cjx82630** [comment]
d42c16b4a4a25119efbc8589a6684d280033cc21
81eb4f8611d0739bf033c16a06a9b27e85478a41
