### ISSUE TITLE
天翼云盘app更新过滤

### ISSUE THREAD

**Issue by ddns6** [easylist/easylistchina#405]
### 列出存在问题的网址 List the website(s) you're having issues:
api.cloud.189.cn

### 什么问题 What happens?
app启动时检测更新请求无法过滤

### 列出你启用的列表 List Subscriptions you're using:
https://anti-ad.net/easylist.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt

### 你的设置 Your settings
- 过滤工具/版本 Adblock Extension/version: AdguardHome v0.107.46

### 附注(列出有问题的规则,截图,建议等) Other details:
求过滤规则
https://api.cloud.189.cn/guns/checkUpgradeInfo.action?clientVersion=9.3.2&versionType=1&rand=1726180330936&clientType=TELEANDROID&model=MI%209&version=9.3.2

https://api.cloud.189.cn/clientVersionCheck.action?rand=1726180336598&clientType=TELEANDROID&version=9.3.2&clientSn=&model=MI%209&channelId=uc&clientParam=&md5Flag=1&initiative=1

**Comment by cjx82630** [comment]
Please refer it to Adguard
