### ISSUE TITLE
Can not block some ads on cocomanhua.com

### ISSUE THREAD

**Issue by CrazyBoyFeng** [easylist/easylistchina#41]
On iOS and Android, these ads are displayed:
* `www.cocomanhua.com/js/ad_/mobile.gif`  
* `www.cocomanhua.com/js/ad_/mobile_f.gif`
* `www.cocomanhua.com/js/ad_/mobile_bottom.gif`
* `www.cocomanhua.com/js/ad_/mobile_right.gif`

And I can not block them manually because they are excluded by:
https://github.com/easylist/easylistchina/blob/418b6e44c84d532b6f99642035963767fd22f684/easylistchina.txt#L18629

**Comment by cjx82630** [comment]
Fixed.Please manually update in 30 minutes.Click on the ABP icon,Preferences,Advanced,Update.
