### ISSUE TITLE
A huge banner on blog.csdn.net

### ISSUE THREAD

**Issue by xxmmllqqqqccqq** [easylist/easylistchina#411]
### 列出存在问题的网址 List the website(s) you're having issues:
[https://blog.csdn.net/Memblaze_2011/article/details/124805088](https://blog.csdn.net/Memblaze_2011/article/details/124805088)

### 什么问题 What happens?
A **huge** banner on top of the page! I think it shold be blocked.

### 列出你启用的列表 List Subscriptions you're using:
ABP filters
EasyList China+EasyList (compliance)
Allow nonintrusive advertising without third-party tracking

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 11 Version 23H2 (Build 22631.4541)
- 浏览器/版本 Browser/version: Microsoft Edge 131.0.2903.86 (正式版本) (64 位) 
- 过滤工具/版本 Adblock Extension/version: Adblock Plus for Microsoft Edge 4.9.4

### 附注(列出有问题的规则,截图,建议等) Other details:
![屏幕截图 2024-12-10 144431](https://github.com/user-attachments/assets/808bcce8-beda-4abb-806a-6a594cb1b247)

**Comment by cjx82630** [comment]
This is self promotion, normal content.If you want to block self promotion on Chinese languge websites,please add subscription(ABP icon,Preferences,Advanced) https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
