### ISSUE TITLE
tryhackme.com

### ISSUE THREAD

**Issue by jellizaveta** [easylist/easylistchina#412]
### Issue:
The following rule incorrectly removes the CAPTCHA box on the login page of TryHackMe:
URL: https://tryhackme.com/r/login

Problematic rule:

```
##div[style^="width: 100%;"][style$="margin: 0px;"] iframe[scrolling="no"][src*="//"][src*="?"][src*="="][src*="&"][width][height][frameborder="0"]
```

### Steps to Reproduce:

1. Open https://tryhackme.com/r/login with EasyList China/AdGuard Chinese filter enabled.
1. Observe that the CAPTCHA box is missing.
1. Disable the rule or add an allowlist exception to confirm the CAPTCHA box reappears.

### Temporary Workaround:
An allow rule has been temporarily added in AdGuard for this website:

```
tryhackme.com#@#div[style^="width: 100%;"][style$="margin: 0px;"] iframe[scrolling="no"][src*="//"][src*="?"][src*="="][src*="&"][width][height][frameborder="0"]
```

### Related Issue:
https://github.com/AdguardTeam/AdguardFilters/issues/194744

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/4d8e67873396b71f38e81eb7b71169c76b30d2a0
