### ISSUE TITLE
Request to whitelist "pt-live.api.autohome.com.cn/api/lives/getliveroom"

### ISSUE THREAD

**Issue by xyyjk** [easylist/easylistchina#413]
Hi EasyList China team,

We recently discovered that the following rule in EasyList China is blocking one of our internal API requests:
||autohome.com.cn/api/lives/getliveroom?$domain=~live.autohome.com.cn

Our domain pt-live.api.autohome.com.cn is used solely for internal purposes related to our media player, which provides live streaming services for users. This API (/api/lives/getliveroom) is a part of our internal system and has no connection to any advertising or user tracking.

Here is an example of a blocked request:
- URL: http://pt-live.api.autohome.com.cn/api/lives/getliveroom?_appid=cms&id=918529&withSeriesInfo=false&withRouteInfo=false&withPublishInfo=false
- Purpose: To fetch live streaming data required by our media player.

The current rule is causing issues for our users as it incorrectly blocks legitimate API requests. We kindly request you to consider one of the following actions:
1. Add our domain (pt-live.api.autohome.com.cn) to the whitelist.
2. Remove this rule or revise it to avoid blocking our API.

Thank you for your time and support. Please let us know if you need any additional information to assist in this review.
Best regards.

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/6110c5e7efdc1c6d23679a9c7d0a63b895a56127
