### ISSUE TITLE
必应广告未屏蔽

### ISSUE THREAD

**Issue by xrgzs** [easylist/easylistchina#414]
### 列出存在问题的网址 List the website(s) you're having issues:

https://cn.bing.com/search?q=proxmox+ve&qs=n&form=QBRE&sp=-1&lq=0&pq=&sc=0-0&sk=&cvid=2178CF00FE75469D90DAB3D3811A9A0B&ghsh=0&ghacc=0&ghpl=

### 什么问题 What happens?

广告未过滤

### 列出你启用的列表 List Subscriptions you're using:

EasyList China + AdGuard Chinese

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 11 24H2 Pro 10.0.26100.2314
- 浏览器/版本 Browser/version: Microsoft Edge 131.0.2903.112
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.61.2

### 附注(列出有问题的规则,截图,建议等) Other details:

![](https://github.com/user-attachments/assets/a1661ec0-95a4-4e86-94f3-a4ae942c1f95)

![](https://github.com/user-attachments/assets/3a4a9b3e-4b5b-458f-b19e-600d2dc00805)

**Comment by cjx82630** [comment]
AdGuard已经处理
