### ISSUE TITLE
aizhantj.com 不是广告联盟

### ISSUE THREAD

**Issue by bala55a** [easylist/easylistchina#417]
### 列出存在问题的网址 List the website(s) you're having issues:
https://github.com/easylist/easylistchina/blob/master/easylistchina.txt#L2001

### 什么问题 What happens?

aizhantj.com 这个域名运营的是网站统计功能，和 tongji.baidu.com 是同类型的产品。
我们不是广告联盟， js 文件中也没有任何广告代码。
产品介绍页:  https://tongji.aizhan.com/

请求您核实。同时请求把 aizhantj.com 这个域名给列表中移除。
非常感谢

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version:

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/1fcfdd72e948b69f2bf4ea88a94eff7c14d07ac8
