### ISSUE TITLE
qidian.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#42]
您好！
网址：`https://www.qidian.com/`
![image](https://user-images.githubusercontent.com/66902050/126959877-a8e4c579-5a95-44f5-9791-e5c699ed87cd.png)
订阅规则：
![image](https://user-images.githubusercontent.com/66902050/126786614-feac6ab4-324b-4902-8cc5-9388c96da462.png)
谢谢！

**Comment by cjx82630** [comment]
不过滤自我推广, 建议自定义.
