### ISSUE TITLE
msn.cn

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#44]
您好！
可能这个反馈到`EasyList`更合适？
![image](https://user-images.githubusercontent.com/66902050/126979783-0bfc42b3-f6f5-4569-8ec9-2a8cacb681a8.png)
谢谢！

**Comment by shenzhiming88** [comment]
@cjx82630 您可能需要使用Microsoft Edge浏览器才能得到类似的效果

**Comment by cjx82630** [comment]
看上去某些规则没有生效,请刷新; 如果是主页, 建议选无广告的网站或空白页

**Comment by shenzhiming88** [comment]
@cjx82630 抱歉，忘记把链接放上来了，您可以使用Microsoft Edge浏览器测试一下
https://www.msn.cn/zh-cn/money/news/%E5%8F%B0%E9%A3%8E-%E7%83%9F%E8%8A%B1-%E7%99%BB%E9%99%86%E5%8D%8A%E5%B0%8F%E6%97%B6%E5%89%8D-%E4%B8%8A%E6%B5%B7%E5%B7%B2%E5%AE%89%E5%85%A8%E8%BD%AC%E7%A7%BB36%E4%B8%87%E4%BA%BA-%E6%97%A0%E4%BA%BA%E5%91%98%E4%BC%A4%E4%BA%A1/ar-AAMwKy8?ocid=winp1taskbar

**Comment by cjx82630** [comment]
30分钟后更新
