### ISSUE TITLE
www.diangongwu.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#46]
您好！
地址：`https://www.diangongwu.com/zhishi/diandongji/143857.html`
感谢！
![网页捕获_1-8-2021_174926_www diangongwu com](https://user-images.githubusercontent.com/66902050/127766698-bc558085-42e9-4bbf-bec9-4991d4cc159c.jpeg)

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
