### ISSUE TITLE
www.qidian.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#47]
您好！
他们说这个应该是广告
https://github.com/easylist/easylist/pull/8516#issuecomment-890719962

**Comment by cjx82630** [comment]
分别是起点的vip卡, 起点的游戏, 所以确实是自我推广, 中文规则不处理自我推广的. 由于也不属于弹窗,或闪烁 也不加入去自我推广列表 .These are self promotions.

**Comment by shenzhiming88** [comment]
> 分别是起点的vip卡, 起点的游戏, 所以确实是自我推广, 中文规则不处理自我推广的. 由于也不属于弹窗,或闪烁 也不加入去自我推广列表 .These are self promotions.

好的，那我到时候再联系一下他们吧，谢谢您
