### ISSUE TITLE
pgdt.gtimg.cn

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#48]
您好！
建议添加
```
||pgdt.gtimg.cn^
```
该域名应该用来保存QQ音乐开屏广告，将该域名屏蔽后，QQ音乐开屏广告消失
实例：http://pgdt.gtimg.cn/141/20204/snscosdownload/SZ/reserved/60fff7c10000e95800000000261156090000008d00004eec?m=428400df768d80ecb881677ed75370ca&ck=428400df768d80ecb881677ed75370ca
![Screenshot_2021-08-03-19-16-52-727_com adguard android](https://user-images.githubusercontent.com/66902050/128007984-14e3c41e-5c09-4b80-9fdf-dc4bcca45c26.jpg)

**Comment by cjx82630** [comment]
||pgdt.gtimg.cn^会误拦游戏页. 如果有网页广告, 请报告网址.

**Comment by shenzhiming88** [comment]
@cjx82630 您好！
请问EasyList China不处理应用内广告吗？
另外请问这个规则会错误拦截吗
```
||pgdt.gtimg.cn/*/snscosdownload/
```

**Comment by shenzhiming88** [comment]
@cjx82630 您好！
请问EasyList China不处理应用内广告吗？
另外请问这个规则会错误拦截吗
```
||pgdt.gtimg.cn/*/snscosdownload/
```

**Comment by shenzhiming88** [comment]
> 只处理网页广告. 你提供的规则有没有对应的网址?

没有。已经在AdGuard规则中修复了。谢谢您！
https://github.com/AdguardTeam/AdguardFilters/pull/90035
