### ISSUE TITLE
此规则屏蔽的是斗鱼首页的背景底图，并非广告内容，请求移除

### ISSUE THREAD

**Issue by dancancer** [easylist/easylistchina#5]
https://github.com/easylist/easylistchina/blob/39bf2fc6d9c59c930735a3ec50d0e161969543b5/easylistchina.txt#L12114

**Comment by cjx82630** [comment]
曾被反馈挂广告

**Comment by cjx82630** [comment]
移除 https://github.com/easylist/easylistchina/commit/8c8ede720b81e75b3957648c793dd8ed9ddf636a
