### ISSUE TITLE
由于规则导致整个网站不可用

### ISSUE THREAD

**Issue by fastnaive** [easylist/easylistchina#51]
这个commit把整个网站的后端服务全部屏蔽了，因为规则设置为了整个网站 GraphQL 的入口，导致网站除了静态内容以外，其他全部不可用  https://github.com/easylist/easylistchina/commit/4ec3963a15c4a9290ab545916e7cce755c26344c 

`/graphql`不是静态资源入口。

事实上网站已经在所有广告上有相同的类名，所以应该把这一条 `||lkong.com/graphql` 修改为
```
lkong.com##.lkong-ads
```

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
