### ISSUE TITLE
Redundancies in easylistchina.txt

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#52]
copy content into https://abpvn.com/ruleChecker/redundantRuleChecker.html

Finished (after 5 seconds)!  8 redundant rules found!

||lflable.com^ has been made redundant by ||lflable.com^
tgfcer.com##.ad_headerbanner has been made redundant by ##.ad_headerbanner
1point3acres.com,xianzhenyuan.cn##.bm.a_c has been made redundant by ##.bm.a_c
1point3acres.com##.wp.a_t has been made redundant by ~aircn.org,~steamcn.com##.wp.a_t
tgfcer.com##div[id^="ad_thread"] has been made redundant by ##div[id^="ad_thread"]
/0xhtml?$script,third-party has been made redundant by /\/[0-9]+[^0-9a-zA-Z]?xhtml\b/$script,third-party
/1xhtml|$script,third-party has been made redundant by /\/[0-9]+[^0-9a-zA-Z]?xhtml\b/$script,third-party
/2xhtml|$script,third-party has been made redundant by /\/[0-9]+[^0-9a-zA-Z]?xhtml\b/$script,third-party

**Comment by sr093906** [comment]
@cjx82630 You only respond to ||lflable.com^. How about other findings? As far as I can see they are redundancies.

**Comment by cjx82630** [comment]
For example, there is `@@||club.tgfcer.com^$generichide` for dealing with anti-adblocker, need to add Specific filter to hide some ads `tgfcer.com##.ad_headerbanner`
`/0xhtml?$script,third-party` is for mobile browsers which not support regular expression filters.

**Comment by sr093906** [comment]
I see. Thanks for clarification.
