### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#53]
warnings encountered while checking the rules:

||*.$image,rewrite=abp-resource:1x1-transparent-gif,third-party,domain=rmdown.com : Unknown option 'rewrite=abp-resource:1x1-transparent-gif'
||*/ad/$rewrite=abp-resource:blank-mp3,domain=huaren.tv : Unknown option 'rewrite=abp-resource:blank-mp3'
||17173cdn.com/20*.mp4$rewrite=abp-resource:blank-mp3,domain=17173.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||8maple.ru/dzcm$rewrite=abp-resource:1x1-transparent-gif,domain=8maple.ru : Unknown option 'rewrite=abp-resource:1x1-transparent-gif'
||banyinjia1.com/media/ads/*.mp4$rewrite=abp-resource:blank-mp3,~third-party : Unknown option 'rewrite=abp-resource:blank-mp3'
||banyinjia11.com/media/ads/*.mp4$rewrite=abp-resource:blank-mp3,~third-party : Unknown option 'rewrite=abp-resource:blank-mp3'
||banyinjia3.com/media/ads/*.mp4$rewrite=abp-resource:blank-mp3,domain=banyinjia11.com|banyinjia3.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||delivery-pc.wasu.cn/d/frontJs/3.0$rewrite=abp-resource:blank-js,domain=wasu.cn : Unknown option 'rewrite=abp-resource:blank-js'
||e9377f.com^$rewrite=abp-resource:blank-mp3,domain=eastday.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||sifakaoshi360.com^$rewrite=abp-resource:blank-mp3,domain=baiduyunbo.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||tongchengoz.com/video/*.mp4$rewrite=abp-resource:blank-mp3,domain=localmv1.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||tongchengoz.com^$rewrite=abp-resource:blank-mp3,domain=localmv1.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||yitongkan.com/splash.xml$rewrite=abp-resource:blank-js,domain=yitongkan.com : Unknown option 'rewrite=abp-resource:blank-js'
huya.com#?##J_spbg:-abp-has( > .J_hot > .drag-elem[data-href*=".360.cn"]) : Domain 'huya.com#?' isn't a valid domain
cn.bing.com#?##b_results > li:-abp-has(.b_adProvider) : Domain 'cn.bing.com#?' isn't a valid domain
6parknews.com#?##d_list > ul > li:-abp-has( > a[href^="http"]:not([href*="6parknews"])) : Domain '6parknews.com#?' isn't a valid domain
isiyuan.net#?##page-list > ul > .layui-row:-abp-has(.ad) : Domain 'isiyuan.net#?' isn't a valid domain
ipv6.baidu.com,www.baidu.com,www1.baidu.com,xueshu.baidu.com#?##content_left > [class]:-abp-has(span[data-tuiguang]) : Domain 'xueshu.baidu.com#?' isn't a valid domain
ipv6.baidu.com,www.baidu.com,www1.baidu.com,xueshu.baidu.com#?##content_left > [style*="important"] : Domain 'xueshu.baidu.com#?' isn't a valid domain
ipv6.baidu.com,www.baidu.com,www1.baidu.com,xueshu.baidu.com#?##content_right > [class]:-abp-has(span[data-tuiguang]) : Domain 'xueshu.baidu.com#?' isn't a valid domain
||s1-a4.ifvod.tv^$rewrite=abp-resource:blank-mp3,domain=ifvod.tv : Unknown option 'rewrite=abp-resource:blank-mp3'
||*^sdtfrom=^$media,rewrite=abp-resource:blank-mp3,domain=qq.com : Unknown option 'rewrite=abp-resource:blank-mp3'
||lts*.qq.com^*.ts?index=$media,rewrite=abp-resource:blank-mp3,domain=qq.com : Unknown option 'rewrite=abp-resource:blank-mp3'

**Comment by cjx82630** [comment]
The redundant check tool is outdated.

**Comment by sr093906** [comment]
@cjx82630 You sure?

**Comment by sr093906** [comment]
I am not a master of Adblock Plus rule syntax but the checks above seems valid. I cannot find 'rewrite=abp-resource:blank-mp3' in official document.

**Comment by cjx82630** [comment]
> I am not a master of Adblock Plus rule syntax but the checks above seems valid. I cannot find 'rewrite=abp-resource:blank-mp3' in official document.

https://help.eyeo.com/adblockplus/how-to-write-filters#rewrite

**Comment by sr093906** [comment]
@cjx82630 Not functional on all editions...

https://testpages.adblockplus.org/en/filters/rewrite
