### ISSUE TITLE
pcbeta.com过滤不彻底，且无法过滤警告弹窗

### ISSUE THREAD

**Issue by huangsijun17** [easylist/easylistchina#55]
去除广告后依然存在底下的白框，并会显示`我们发现您似乎启用了广告屏蔽功能，请将 bbs.pcbeta.com 加入白名单，解除广告屏蔽后继续访问。`的悬浮窗或弹窗。

**Comment by cjx82630** [comment]
请自定义小脚本规则,请查看 https://gitee.com/cjx82630/cjxlist/raw/master/chinese.txt 或 https://raw.githubusercontent.com/cjx82630/cjxlist/master/chinese.txt 复制内容到自定义(点击ABP图标>齿轮>高级>我的过滤列表下文本框)

**Comment by huangsijun17** [comment]
> 请自定义小脚本规则,请查看 https://gitee.com/cjx82630/cjxlist/raw/master/chinese.txt 或 https://raw.githubusercontent.com/cjx82630/cjxlist/master/chinese.txt 复制内容到自定义(点击ABP图标>齿轮>高级>我的过滤列表下文本框)

1. 底下的框使用的是随机class，难以使用自定义规则屏蔽。
2. 悬浮窗是div窗口可以屏蔽，但弹窗是JS代码……
