### ISSUE TITLE
cn.bing.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#58]
您好！
网址：https://cn.bing.com/search?q=%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98&cvid=62c56ffd14844dcfba453cb98537321d&aqs=edge.0.0l8j69i61.2279j0j1&pglt=163&FORM=ANNTA1&PC=U531
此处的广告似乎没有过滤，请检查一下，谢谢
![image](https://user-images.githubusercontent.com/66902050/132967625-dc02b83b-427c-44f6-913a-684491fef46c.png)

**Comment by cjx82630** [comment]
请用ABP测试.

**Comment by shenzhiming88** [comment]
现在使用uBO也没有广告了，可能是规则又更新了
