### ISSUE TITLE
zhidao.baidu.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#60]
您好！
https://github.com/easylist/easylist/pull/9071
为什么要允许这个元素呢？这个元素正是分享按钮，Fanboy's Annoyance的功能包括屏蔽分享按钮，并且也没有破坏网页
https://github.com/easylist/easylistchina/blob/a4d9776df67766a26ac4f2f25e53638b18bf775d/easylistchina.txt#L19353

**Comment by cjx82630** [comment]
因为以前出现过bug. 无法点击"展开全文". 既然网站已经修复, 可以移除.
