### ISSUE TITLE
ddrk.me

### ISSUE THREAD

**Issue by Ethan3157** [easylist/easylistchina#61]
ios15
Safari
Adblock 2.0.15(95)
网址:https://ddrk.me
         https://www.mp4er.com
两个网站问题差不多都是右下角悬浮广告，另外第一个网站还有上方的图片广告。
![927CFF74-7773-4ADE-91FE-C63AE1CFB254](https://user-images.githubusercontent.com/38642486/132991348-4375ef7c-4786-4f2c-8b33-1b7bf3fa97c9.png)
![4FFCB1E1-B813-4C7E-97D4-C2F46FB1CA61](https://user-images.githubusercontent.com/38642486/132991358-6fd3eaf1-a524-419d-a46b-ef463ae80838.png)

**Comment by cjx82630** [comment]
你规则没生效. 我用火狐安卓版+UBO没见广告.

**Comment by Ethan3157** [comment]
你说它没生效吧，他确实过滤掉了一些网页的广告，比如百度。
![PNG图像](https://user-images.githubusercontent.com/38642486/133011494-a90bd447-e319-48ab-aa82-7e067d27a4d8.png)
![PNG图像 2](https://user-images.githubusercontent.com/38642486/133011533-fcae71a8-1e14-4651-bb16-ed5a8169e899.png)
但又有一些网站Windows版chrome上浏览没有广告，但用safari就有广告，为什么会出现这种情况呀？
我应该联系adblock的客服人员吗？

**Comment by cjx82630** [comment]
建议联系Adblock
