### ISSUE TITLE
nfmovies.com无法访问

### ISSUE THREAD

**Issue by Sworke** [easylist/easylistchina#62]
由于nfmovies.com有反ABP，导致打不开网页
似乎是下面两个元素，在删除后可正常屏蔽广告及访问

> nfmovies.com#?#div[id]:-abp-has(>img[onclick="openurl()"])

> ||nfmovies.com/static/*.jpg

**Comment by cjx82630** [comment]
请自定义小脚本规则,请查看  https://raw.githubusercontent.com/cjx82630/cjxlist/master/chinese.txt 复制内容到自定义(点击ABP图标>齿轮>高级>我的过滤列表下文本框)
