### ISSUE TITLE
zhihu.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#64]
您好！
这一行规则已经包含进了Fanboy列表中，请删除
https://github.com/easylist/easylistchina/blob/22327098ff89316956e9c1f981bd302578c8745b/easylistchina.txt#L19418
这一行规则好像没看出来有什么用，原本就没有屏蔽“喜欢”按钮
https://github.com/easylist/easylistchina/blob/22327098ff89316956e9c1f981bd302578c8745b/easylistchina.txt#L19419

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.
