### ISSUE TITLE
cowtransfer.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#66]
您好！
该规则经过简单测试之后似乎无法复现
https://github.com/easylist/easylistchina/blob/f38078329595d8246d603c4f3b8f1aea537684b0/easylistchina.txt#L19462

**Comment by cjx82630** [comment]
手机验证码登录后见误拦

**Comment by shenzhiming88** [comment]
@cjx82630 我测试了一下，可以使用手机验证码正常登录，登陆后分享文件之类的功能也未见到误拦
