### ISSUE TITLE
baidu.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#67]
您好
应该去除掉`baidu.com`，已经包含于`fanboy_social_allowlist_general_hide.txt`中
https://github.com/easylist/easylistchina/blob/f38078329595d8246d603c4f3b8f1aea537684b0/easylistchina.txt#L19448
参见：
https://github.com/easylist/easylist/blob/57a7ae34e7994f14db6e35dc756b8e42fa961a17/fanboy-addon/fanboy_social_allowlist_general_hide.txt#L306

**Comment by cjx82630** [comment]
30分钟后更新.

**Comment by shenzhiming88** [comment]
@cjx82630

**Comment by shenzhiming88** [comment]
@cjx82630 您好！好像还是没有更新
另外您能否向他们那边进行反馈呢？或者申请Easylist库的写入权限。
