### ISSUE TITLE
bilibili.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#68]
您好！
这一行中的bilibili.com可以去除
https://github.com/easylist/easylistchina/blob/546d709a5723120f4c07b346dad018ca88bec8bf/easylistchina.txt#L19434
https://github.com/easylist/easylist/pull/9163

**Comment by cjx82630** [comment]
是关注按钮

**Comment by shenzhiming88** [comment]
> 是关注按钮

已经被修复了，上面给的有链接

**Comment by shenzhiming88** [comment]
@cjx82630

**Comment by cjx82630** [comment]
30分钟后更新.
