### ISSUE TITLE
可能重复/无效的规则

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#70]
您好！

1. https://github.com/easylist/easylistchina/blob/5a2c148d6e738a6137e7134ee2dd6242aed971eb/easylistchina.txt#L19517
这一行已经被他们修复
https://github.com/easylist/easylist/commit/41c79b55863753c55cf02a0c265eff5025650ccd#diff-81991527611f276236f88e6898a8a317acdfb41cfcb0443589c19b8a9b7cefc1R251

2. https://github.com/easylist/easylistchina/blob/5a2c148d6e738a6137e7134ee2dd6242aed971eb/easylistchina.txt#L19530
该网页反广告，关闭广告过滤器后，重定向至`http://iyfbodn.com/`，无法打开，并且该网页被报告为钓鱼网站

3. https://github.com/easylist/easylistchina/blob/5a2c148d6e738a6137e7134ee2dd6242aed971eb/easylistchina.txt#L19512
看名称应该与关注有关，但似乎找不到该元素（视频/直播/个人主页）

其实我还是希望您可以直接与EasyList他们联系，把这些规则全部都合并到主列表中，而不是在该列表中修复。谢谢！

**Comment by shenzhiming88** [comment]
@cjx82630

**Comment by cjx82630** [comment]
https://www.bilibili.com/anime
用户可以反馈, 但有时要等三五天.

**Comment by shenzhiming88** [comment]
@cjx82630 您好，那就把上面的规则整理一下吧，谢谢

**Comment by shenzhiming88** [comment]
@cjx82630
