### ISSUE TITLE
[NSFW] gaybeeg.info

### ISSUE THREAD

**Issue by felippesantos46** [easylist/easylistchina#71]
Hey @cjx82630 

The following issue was at the Portuguese IR, but i believe it's a Chinese webpage [gaybeeg](https://gaybeeg.info/): 
<img width="1440" alt="Screenshot 2021-09-30 at 12 25 30" src="https://user-images.githubusercontent.com/65717387/135485250-058f77b9-7f69-495d-ae4c-55b02126d905.png">

- After you click in almost all of the content on the page, we have requests to another pages. 

- To reproduce, you can simply click in any of the images, after you open one of the presented content, as well as the header of the webpage.

- I don't know if snippets would be the best solution, but i could end this popup pages with the following blocking filters: 
```
||romepoptahul.com$script
||ployea.com$script
||www.lghdoxzulv.com$script

```

**Comment by cjx82630** [comment]
I think it is an [US. site according alexa](https://www.alexa.com/siteinfo/gaybeeg.info) It is in English language.  Could you send the issue to Easylist?

**Comment by felippesantos46** [comment]
Sure thing. As i do not have writing permissions to transfer the Issue. I already create one in there and i'm closing this one ! thank you !
