### ISSUE TITLE
dangdang.com

### ISSUE THREAD

**Issue by DeepChirp** [easylist/easylistchina#78]
您可能需要登录查看
http://info.safe.dangdang.com/Myarchives.php
```
##.ads_narrow
##.foot_tip_ad
```
![image](https://user-images.githubusercontent.com/66902050/136580916-edb220a9-70ad-416d-8733-79905bbf5253.png)
![image](https://user-images.githubusercontent.com/66902050/136580982-9b29e83a-db69-4b32-b72a-9aa77d29dcb0.png)

**Comment by cjx82630** [comment]
不拦截自我推广.
