### ISSUE TITLE
removed obsolete filters

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#79]
```
sogou.com#@##shareContent
harrynull.tech#@##sharelist
hotjob.cn#@#.SOCIAL
softblog.tw#@#.dshare
sui.com#@#.fb-btn
oschina.net#@#.follow-btn
bilibili.com#@#.follow-wrapper
music.163.com#@#.p-share
weiyun.com#@#.share-link
storm.mg#@#.social_btn
@@||10086.cn/framework/modules/sdc.js
@@||baidu.com/hm.$domain=clgod.com
@@||gtimg.com/qqcdn/*/beacon.min.js$script,domain=qq.com
```

下面是具体的commit

```
sogou.com#@##shareContent
```
https://github.com/easylist/easylist/commit/dc1082f59d670cddc95c24a0c78b3585e1b11b09

```
harrynull.tech#@##sharelist
```
https://github.com/easylist/easylist/commit/8cd4f60f8c1a1ac890e386e3fee5edeca357cce7

```
hotjob.cn#@#.SOCIAL
```
该规则无效。
https://www.hotjob.cn/wt/GoerTek/web/index/CompGoerTekIndex_campus

```
softblog.tw#@#.dshare
```
https://github.com/easylist/easylist/commit/a9915f29b2f4a115749cd7176825d95d31b9f094

```
sui.com#@#.fb-btn
```
https://github.com/easylist/easylist/commit/25d21dabad2b6252bccbe50c7dbea4f09cdb2ed8

```
oschina.net#@#.follow-btn
```
https://github.com/easylist/easylist/commit/1711f53dd4ea6956681192270383e7f232ec6920

```
bilibili.com#@#.follow-wrapper
```
https://github.com/easylist/easylist/commit/f524a83dfc4f18089085c8b5a8044bd2627ad377

```
music.163.com#@#.p-share
```
https://github.com/easylist/easylist/commit/41c79b55863753c55cf02a0c265eff5025650ccd

```
weiyun.com#@#.share-link
```
https://github.com/easylist/easylist/commit/e77a9a52aa87ca6cdfbf7141237f98c220e6f71b

```
storm.mg#@#.social_btn
```
https://github.com/easylist/easylist/commit/a9915f29b2f4a115749cd7176825d95d31b9f094

```
 @@||10086.cn/framework/modules/sdc.js
```
https://github.com/easylist/easylist/commit/cebaae142d25799be8e435b933299eea0f179691

```
@@||gtimg.com/qqcdn/*/beacon.min.js$script,domain=qq.com
```
https://github.com/easylist/easylist/commit/530dd6b1a04254c5f845b2ab641ee2af3ca1f91a

**Comment by shenzhiming88** [comment]
```
 @@||10086.cn/framework/modules/sdc.js
```

https://github.com/easylist/easylist/commit/cebaae142d25799be8e435b933299eea0f179691

```
 @@||adobedtm.com^*/satelliteLib-$script,domain=samsungmembers.cn
```
拦截该脚本似乎不会导致任何问题
@cjx82630

**Comment by shenzhiming88** [comment]
@cjx82630

**Comment by cjx82630** [comment]
b6d13d21d13c65b4c1045664008cbaeff6dddf68 我检查过了,移除无效规则. 30分钟后更新.
