### ISSUE TITLE
(Possible) Inactive Entries

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#8]
HTTP Code 404

Following entries returned a 404 code to automated queries. No manual verification was made to the results. 

1.soufy.cn    
104.195.62.12    
119.29.207.87    
121.40.25.88    
139.196.166.21    
1711811.com
182.92.81.104    
23.91.3.114    
4006825178.com
51dengshan.cn    
52homie.cn    
57union.com    
5glyqw.com    
61.174.50.211    
7gg.cc    
7xi9g1.com1.z0.glb.clouddn.com    
80sjw.com    
86uk.com    
92mile.com    
a.nowscore.com    
aakkzzz.com    
adm.cloud.cnfol.com    
adm.xmfish.com    
adnetpub.yaolan.com    
adpubs.yaolan.com    
ai.bioon.com    
aimiyz.com    
aishake.cn    
aiwanma99.com    
alifixed.cn       
alimama.alicdn.com
appimg.0575bbs.com    
atanx.alicdn.com
b.unjs.com    
badding.oss-ap-southeast-1.aliyuncs.com    
bbba8.com    
bdm.911cha.com    
biaoshipai.net    
bk9gun.vpser.net    
boweineng.cn    
bslmw.com    
bvoer.com    
cdn-mutil-object.cn-hangzhou.oss-cdn.aliyun-inc.com    
cfhijdsb.cn    
chinawms.cn    
cmm.xmfish.com    
cnhbxx.com    
cojia.net    
continuedsys.cn    
dasheducation.cn    
dashet.com    
dbojetp.cn    
ddskyuu.com    
de.as.pptv.com    
delivery.wasu.cn    
detuns.com    
diuling.com    
dssdr.top    
dvs.china.com    
dzrenju2.cn    
ecuwa.cn       
egjq.com.cn    
elvx.top    
fanglinwang.cn    
free-cdn.oss-cn-shanghai.aliyuncs.com    
gdlvbiaokeji.cn    
greenbetterkids.com    
gutouwang.net    
gzmzts.com    
hades.qyer.com    
hdapp1008-a.akamaihd.net    
heygugu.com    
i.zhuoyaju.com    
immedlinkum.info    
iqiyi.kim    
iqiyi.pub    
jianbangjiaoyu.com    
just9229.cn    
k1.wanwenwan.cn    
lzytt.com    
market.21cn.com    
meituan.xn--io0a7i    
mkaqh.cn    
moonwish.com.cn    
mysty.com.cn    
ndtzx.com    
nduop.com    
pfizer.com.tw    
picbr.com    
rdxhrd.com    
runkao.net    
rwjfs.com    
s9w.cc    
sa.sina.cn    
ssp.njxzwh.com    
sssvd.china.com    
swtkc.cn    
tencent.xn--io0a7i    
tjqonline.cn    
tngmn.com    
txzs168.net    
uadsaa.com
v1.taksh.cn    
w010w.com.cn    
watchsk.com      
xhct66.com    
xulizui6.com    
ytop8.com    
z.nowscore.com    
zazkkk.com    
zhanjiangletian.com    
zhivalley.cn    
zhuangzhaibancai.cn    
zkba9.cn    
zmlled.cn

**Comment by cjx82630** [comment]
I used whois to check most of them, many domains have not expired yet, if they expire in the future, I will remove them.

**Comment by sr093906** [comment]
> I used whois to check most of them, many domains have not expired yet, if they expire in the future, I will remove them.

So, none of the over 100 domains are inactive because of the whois data. you sure?

**Comment by cjx82630** [comment]
"soufy.cn"
Expiration Time: 2026-09-22 13:29:32
"1711811.com"
   Registry Expiry Date: 2021-05-25T18:52:21Z
Registrar Registration Expiration Date: 2021-05-26T02:52:21Z
Registrar Registration Expiration Date: 2021-05-26T02:52:21Z
"4006825178.com"
   Registry Expiry Date: 2021-06-02T18:01:11Z
Registrar Registration Expiration Date: 2021-06-03T02:34:16Z
"51dengshan.cn"
Expiration Time: 2021-11-28 16:34:02
"52homie.cn"
Expiration Time: 2021-08-27 07:04:44
"57union.com"
   Registry Expiry Date: 2021-06-15T18:16:16Z
"5glyqw.com"
   Registry Expiry Date: 2021-12-08T19:27:06Z
"7gg.cc"
   Registry Expiry Date: 2022-01-15T09:00:23Z
Registrar Registration Expiration Date: 2022-01-15T04:00:23Z
"clouddn.com"
   Registry Expiry Date: 2021-04-14T08:23:52Z
Registrar Registration Expiration Date: 2022-04-14T08:23:52Z
"80sjw.com"
   Registry Expiry Date: 2021-08-20T18:10:16Z
"86uk.com"
   Registry Expiry Date: 2021-07-14T21:53:09Z
Registrar Registration Expiration Date: 2021-07-14T21:53:09Z 
"  92mile.com
   Registry Expiry Date: 2021-09-11T18:23:32Z
"nowscore.com"
   Registry Expiry Date: 2027-10-28T11:59:59Z
"aakkzzz.com"
   Registry Expiry Date: 2021-07-03T01:16:35Z
Registrar Registration Expiration Date: 2021-07-03T01:16:35Z
"cnfol.com"
   Registry Expiry Date: 2023-11-01T00:18:49Z
Registrar Registration Expiration Date: 2023-10-31T04:00:00Z
"xmfish.com"
   Registry Expiry Date: 2023-09-13T06:41:04Z
Registrar Registration Expiration Date: 2023-09-13T01:41:04Z
"yaolan.com"
   Registry Expiry Date: 2021-10-08T09:46:18Z
"bioon.com"
   Registry Expiry Date: 2022-04-18T09:02:06Z
"aimiyz.com"
   Registry Expiry Date: 2021-05-12T03:55:41Z
Registrar Registration Expiration Date: 2021-05-11T22:55:41Z
"aishake.cn"
Expiration Time: 2021-11-19 19:08:47
"aiwanma99.com"
   Registry Expiry Date: 2021-06-01T08:01:57Z
Registrar Registration Expiration Date: 2021-06-01T08:01:57Z
"alifixed.cn"
Expiration Time: 2021-06-21 17:51:45
"alicdn.com"
   Registry Expiry Date: 2022-06-25T09:24:11Z
"0575bbs.com"
   Registry Expiry Date: 2023-04-01T08:27:25Z
Registrar Registration Expiration Date: 2023-04-01T00:00:00Z
"unjs.com"
   Registry Expiry Date: 2022-04-02T05:11:20Z
"aliyuncs.com"
   Registry Expiry Date: 2023-04-01T07:23:40Z
"bbba8.com"
   Registry Expiry Date: 2022-02-18T05:58:23Z
Registrar Registration Expiration Date: 2021-02-17T07:00:00Z
"911cha.com"
   Registry Expiry Date: 2023-03-11T04:07:21Z
Registrar Registration Expiration Date: 2023-03-10T23:07:21Z
"biaoshipai.net"
   Registry Expiry Date: 2021-04-23T14:06:21Z
"vpser.net"
   Registry Expiry Date: 2023-03-18T14:56:23Z
"boweineng.cn"
Expiration Time: 2022-02-27 23:57:41
"bslmw.com"
   Registry Expiry Date: 2022-02-18T11:29:49Z
Registrar Registration Expiration Date: 2021-02-18T07:00:00Z
"bvoer.com"
   Registry Expiry Date: 2021-03-21T18:31:53Z
Registrar Registration Expiration Date: 2021-03-21T07:00:00Z
"aliyun-inc.com"
   Registry Expiry Date: 2021-09-22T05:10:51Z
"cfhijdsb.cn"
Expiration Time: 2021-06-13 15:13:59
"chinawms.cn"
Expiration Time: 2021-11-11 20:15:35
"cnhbxx.com"
   Registry Expiry Date: 2021-05-19T19:24:20Z
"cojia.net"
   Registry Expiry Date: 2022-06-12T04:44:12Z
"continuedsys.cn"
Expiration Time: 2022-02-27 23:51:44
"dasheducation.cn"
Expiration Time: 2021-07-10 17:30:32
"dashet.com"
   Registry Expiry Date: 2021-04-24T09:07:25Z
"dbojetp.cn"
Expiration Time: 2021-04-16 14:20:59
"ddskyuu.com"
   Registry Expiry Date: 2021-09-16T08:16:31Z
Registrar Registration Expiration Date: 2021-09-16T08:16:31Z
"pptv.com"
   Registry Expiry Date: 2024-03-14T18:03:31Z
Registrar Registration Expiration Date: 2024-03-13T16:00:00Z
"wasu.cn"
Expiration Time: 2028-10-29 20:26:29
"detuns.com"
   Registry Expiry Date: 2021-03-21T18:50:39Z
Registrar Registration Expiration Date: 2021-03-21T07:00:00Z
"diuling.com"
   Registry Expiry Date: 2022-02-02T19:26:15Z
"dssdr.top"
Registry Expiry Date: 2021-12-03T22:11:08Z
"china.com"
   Registry Expiry Date: 2028-08-23T04:00:00Z
"dzrenju2.cn"
Expiration Time: 2021-11-10 04:28:12
"ecuwa.cn"
Expiration Time: 2021-04-16 14:21:18
"egjq.com.cn"
Expiration Time: 2021-06-01 11:45:21
"elvx.top"
Registry Expiry Date: 2021-10-15T05:21:46Z
"fanglinwang.cn"
Expiration Time: 2021-07-26 17:10:52
"gdlvbiaokeji.cn"
Expiration Time: 2021-09-15 04:03:14
"greenbetterkids.com"
   Registry Expiry Date: 2021-04-16T18:46:49Z
Registrar Registration Expiration Date: 2021-04-16T00:00:00.000Z
"gutouwang.net"
   Registry Expiry Date: 2021-08-08T05:08:54Z
Registrar Registration Expiration Date: 2021-08-08T05:08:53.0Z
"gzmzts.com"
   Registry Expiry Date: 2021-05-24T01:42:16Z
Registrar Registration Expiration Date: 2021-05-23T07:00:00Z
"qyer.com"
   Registry Expiry Date: 2023-06-05T10:00:47Z
Registrar Registration Expiration Date: 2023-06-04T16:00:00Z
"akamaihd.net"
   Registry Expiry Date: 2022-09-14T20:35:31Z
"heygugu.com"
   Registry Expiry Date: 2021-09-23T18:53:04Z
Registrar Registration Expiration Date: 2021-09-23T18:53:04.0Z
"zhuoyaju.com"
   Registry Expiry Date: 2022-02-17T19:46:27Z
Registrar Registration Expiration Date: 2022-02-17T14:46:27Z
"immedlinkum.info"
Registry Expiry Date: 2021-10-12T22:15:28Z
Registrar Registration Expiration Date: 2021-10-12T22:15:28Z
"iqiyi.kim"
Registry Expiry Date: 2021-08-30T06:23:30Z
"iqiyi.pub"
Registry Expiry Date: 2021-08-30T06:23:27Z
"jianbangjiaoyu.com"
   Registry Expiry Date: 2021-12-08T19:05:30Z
Registrar Registration Expiration Date: 2021-12-08T07:00:00Z
"just9229.cn"
Expiration Time: 2021-08-11 23:21:42
"wanwenwan.cn"
Expiration Time: 2021-03-05 12:52:02
"lzytt.com"
   Registry Expiry Date: 2021-03-21T01:56:41Z
Registrar Registration Expiration Date: 2021-03-20T07:00:00Z
"21cn.com"
   Registry Expiry Date: 2027-02-08T05:00:00Z
Registrar Registration Expiration Date: 2027-02-08T04:00:00Z
"meituan.xn--io0a7i"
"mkaqh.cn"
Expiration Time: 2021-04-16 15:07:14
"moonwish.com.cn"
Expiration Time: 2022-01-31 19:51:59
"mysty.com.cn"
Expiration Time: 2021-11-14 18:01:08
"ndtzx.com"
   Registry Expiry Date: 2021-09-01T18:07:24Z
Registrar Registration Expiration Date: 2021-09-02T02:07:24Z
Registrar Registration Expiration Date: 2021-09-02T02:07:24Z
"nduop.com"
   Registry Expiry Date: 2021-03-21T18:33:27Z
Registrar Registration Expiration Date: 2021-03-21T07:00:00Z
"pfizer.com.tw"
   Record expires on 2027-07-08 (YYYY-MM-DD)
"picbr.com"
   Registry Expiry Date: 2021-03-21T18:27:00Z
Registrar Registration Expiration Date: 2021-03-21T00:00:00.000Z
"rdxhrd.com"
   Registry Expiry Date: 2022-03-03T05:46:26Z
Registrar Registration Expiration Date: 2021-03-02T07:00:00Z
"runkao.net"
   Registry Expiry Date: 2021-07-18T17:05:54Z
"rwjfs.com"
   Registry Expiry Date: 2021-12-17T19:29:29Z
Registrar Registration Expiration Date: 2021-12-17T14:29:29Z
"s9w.cc"
   Registry Expiry Date: 2021-12-08T07:43:08Z
"sina.cn"
Expiration Time: 2022-03-17 12:48:36
"njxzwh.com"
   Registry Expiry Date: 2023-03-02T14:25:10Z
Registrar Registration Expiration Date: 2023-03-01T16:00:00Z
"swtkc.cn"
Expiration Time: 2021-08-22 14:43:51
"tencent.xn--io0a7i"
"tjqonline.cn"
Expiration Time: 2023-04-19 16:11:01
"tngmn.com"
   Registry Expiry Date: 2022-02-27T19:10:18Z
"txzs168.net"
   Registry Expiry Date: 2021-08-19T05:29:35Z
Registrar Registration Expiration Date: 2021-08-19T00:00:00Z
"uadsaa.com"
   Registry Expiry Date: 2021-08-23T07:10:44Z
Registrar Registration Expiration Date: 2021-08-23T02:10:44Z
"taksh.cn"
Expiration Time: 2021-10-02 11:00:30
"w010w.com.cn"
Expiration Time: 2021-10-26 16:17:45
"watchsk.com"
   Registry Expiry Date: 2021-05-26T22:25:58Z
Registrar Registration Expiration Date: 2021-05-26T22:25:58
"xhct66.com"
   Registry Expiry Date: 2021-10-10T18:05:24Z
Registrar Registration Expiration Date: 2021-10-10T00:00:00.000Z
"xulizui6.com"
   Registry Expiry Date: 2022-07-28T09:08:09Z
Registrar Registration Expiration Date: 2022-07-28T09:08:09Z
"ytop8.com"
   Registry Expiry Date: 2021-03-27T11:59:49Z
"zazkkk.com"
   Registry Expiry Date: 2021-06-15T10:11:27Z
Registrar Registration Expiration Date: 2021-06-15T10:11:27Z
"zhanjiangletian.com"
   Registry Expiry Date: 2022-03-23T18:39:30Z
Registrar Registration Expiration Date: 2022-03-24T02:39:30Z
"zhivalley.cn"
Expiration Time: 2021-07-07 10:42:00
"zhuangzhaibancai.cn"
Expiration Time: 2021-10-08 17:56:18
"zkba9.cn"
Expiration Time: 2021-04-16 15:09:11
"zmlled.cn"
Expiration Time: 2021-04-24 11:31:39

**Comment by sr093906** [comment]
@cjx82630 Forgive me if I am wrong. You just use the data of BASE DOMAIN to indicate the sub-domain you blocked in the filter are still active.

ARE YOU KIDDDING?

**Comment by sr093906** [comment]
With such method, then none of the domain filters related to big corps can be removed once added since the base domain will always active unless the corporations go bust one day.

**Comment by cjx82630** [comment]
Just to advertising only host names. Most of them you listed are ads union only.

**Comment by sr093906** [comment]
@cjx82630 Also, based on the above-mentiond standard, which relies on whois expiration, could you explain why you removed 'beizhoujt.cn' from the filter this morning and marked it as 'obsolete'. 

https://github.com/easylist/easylistchina/compare/easylist:36b56c3...easylist:647cc8a

I checked the domain's whois data, which showed it will expire at 2022-01-07 15:24:06

https://who.is/whois/beizhoujt.cn

And a manual check shows the connection to the domain is reset with VPN on.

**Comment by cjx82630** [comment]
It is redundant filters, it is still in the easylist china.

**Comment by sr093906** [comment]
@cjx82630 https://github.com/easylist/easylistchina/compare/easylist:cb2b527...easylist:36b56c3

https://whois.chinaz.com/118ex.cn 
https://whois.chinaz.com/16guu.com  
https://whois.chinaz.com/2hqd0b.cn

...

**Comment by cjx82630** [comment]
You should click on "立即更新" when you are browsing whois.chinaz.com
with latest info, 
16guu.com Expiry Date: 2021年01月16日
2hqd0b.cn Expiry Date: 2021年01月17日
118ex.cn already dead.

**Comment by sr093906** [comment]
@cjx82630 
![image](https://user-images.githubusercontent.com/8369201/110088706-2a394d00-7dd0-11eb-8fa6-0c7b28c0f3ca.png)

from ICANN

**Comment by cjx82630** [comment]
Looks like I need to double check.

**Comment by sr093906** [comment]
@cjx82630 Welcome. I can provide more earlier examples. 

https://github.com/easylist/easylistchina/commit/8c83b091da356d15ac5054840169c962a39cfd94

![image](https://user-images.githubusercontent.com/8369201/110092355-7a1a1300-7dd4-11eb-992a-32bee52140ff.png)

https://github.com/easylist/easylistchina/commit/e51082d78c93733c90fe50021e896c157b6e7b40

![image](https://user-images.githubusercontent.com/8369201/110092520-a6359400-7dd4-11eb-956a-2c6ad48362e0.png)

The two domains are both unresponsive though.

So, it seems the standard to remove domain rules varies from time to time, isn't it?

**Comment by cjx82630** [comment]
pic12x20.com was block in the first place, until I noticed  it would break (NSFW)https://www.2a5b.com/t/666699.html
popin.cc the whole domain should not be block, it was handled by Easylist.

**Comment by cjx82630** [comment]
And how do you check the info of domain names? websites, bat, exe?

**Comment by sr093906** [comment]
@cjx82630 I got it, popin.cc is not your problem. You should blame others. OK. And pic12x20.com is a false positive because it will break a NSFW site. 

but what about https://github.com/easylist/easylistchina/issues/8#issuecomment-791255017? 

Also, what I care most is why do you insist domains that return 404 page/code shouldn't be removed?

**Comment by sr093906** [comment]
For the second question, you mean the “automated queries” or the whois data?

**Comment by cjx82630** [comment]
I used whois.exe to check .gold domains, but it is not perfect.  I'll find a new way to check then.
As long as someone owns domain names that had been advertised, there is alway a possibility of re-advertisement. 
What tools do you use to get whois data?

**Comment by cjx82630** [comment]
popin.cc  check it out  https://github.com/AdguardTeam/AdguardFilters/issues/62998

**Comment by sr093906** [comment]
Sorry for the long delay as I have no intention to answer the question in the first place since you actually ignored all the domains I reported in this issue... But I changed my idea and finally decided to reply. Just take it as something to your long-time work on the filter list for mainland China, Hong Kong, Taiwan and possibly other areas with ethnic Chinese.

I usually use ICANN Lookup. The sysinternal's whois tool doesn't support the .gold TLD and also many uncommon ones.

For single query, I suggest two utilities.

https://www.karenware.com/powertools/karens-whois (whois.iana.org)
https://gwhois.org

For multiple entries, you can try Nirsoft's Whois tool with whois-servers.txt and/or whois-server-list.xml. 

**Caution: vulnerabilities exist in the vendor's tools, see http://borncity.com/win/2020/04/16/dll-hijacking-vulnerabilities-in-nirsoft-tools/**

https://www.nirsoft.net/utils/whois_this_domain.html

> Creating whois-servers.txt
Starting from version 1.20, you can create your own WHOIS servers list to override the default servers defined by WhoisThisDomain.
In order to use this feature, follow the instructions below:
Create a file named 'whois-servers.txt' in the same folder of WhoisTD.exe
Add the needed servers to the list. Each line should contain the domain extension, a space character, and then the whois server address. For example:
gov whois.nic.gov
com rs.internic.net 
il whois.isoc.org.il
ir whois.nic.ir
In the next time that you run WhoisThisDomain, the specified servers will be used instead of the default servers list stored in WhoisThisDomain.
Be aware that WhoisThisDomain only supports WHOIS servers in port 43. It doesn't support Web-based WHOIS requests.

Using whois-server-list.xml
Starting from version 2.35, you can download the whois servers list xml file from https://github.com/whois-server-list/whois-server-list, put the file as whois-server-list.xml in the same folder of WhoisTD.exe and WhoisThisDomain will automatically extract the right whois server from this file. This whois-server-list.xml file is more updated and contains more whois servers than the internal whois servers list of WhoisThisDomain.

If you use linux, there are more choices.

https://superuser.com/questions/758647/how-to-whois-new-tlds

**Comment by cjx82630** [comment]
I have found a way to obtain whois data, and I will soon start cleaning up outdated domain names. Your feedbacks will be processed later.
