### ISSUE TITLE
移动端贴吧广告

### ISSUE THREAD

**Issue by MkQtS** [easylist/easylistchina#88]
Url: https://tieba.baidu.com/f?kw=potplayer
截图：
![2021_1122-1531_11](https://user-images.githubusercontent.com/81752398/142820937-f6ecbfb1-73e5-4f66-b751-097e904cc65b.png)

**Comment by MkQtS** [comment]
@cjx82630 
帖子评论区中也有广告
![2021_1122-1553_29](https://user-images.githubusercontent.com/81752398/142823564-6a3178ff-f5f5-4e86-9981-6ae09a88841c.png)
![2021_1122-1553_41](https://user-images.githubusercontent.com/81752398/142823596-4ac9d0ca-746f-498c-925d-7b6ca9508f5e.png)

**Comment by cjx82630** [comment]
30分钟后更新. 但网页版劣化太厉害, 不推荐.
Fixed.Please manually update in 30 minutes.
