### ISSUE TITLE
(Possible) Useless Entries (0-9)

### ISSUE THREAD

**Issue by sr093906** [easylist/easylistchina#9]
Redirect to search engine:

05qwmtwxa3ev.com 
0937js.com 
1jsskipuf8sd.com

404:

88eg.cn

Empty response:

4z5o27.cn

**Comment by cjx82630** [comment]
Thanks. I usually check whether the domain name has expired at intervals. I will remove the domain name if it has expired.

**Comment by cjx82630** [comment]
\ 05qwmtwxa3ev.com
   Registry Expiry Date: 2021-07-03T04:54:12Z

\ 0937js.com
   Registry Expiry Date: 2021-04-10T18:41:04Z

Registrar Registration Expiration Date: 2021-04-11T02:41:04Z

\ 1jsskipuf8sd.com
   Registry Expiry Date: 2021-05-03T17:02:39Z

Registrar Registration Expiration Date: 2021-05-03T17:02:00.00Z

Registrar Registration Expiration Date: 2021-05-03T17:02:00.00Z

\ 88eg.cn
Expiration Time: 2022-02-26 09:11:04
\ 4z5o27.cn
Expiration Time: 2021-03-20 04:02:08
