### ISSUE TITLE
tingfm.com

### ISSUE THREAD

**Issue by shenzhiming88** [easylist/easylistchina#99]
https://tingfm.com/radio/119
这里还有广告清理后的残留物，请处理一下，谢谢
![image](https://user-images.githubusercontent.com/66902050/146565860-446b2805-a448-447e-a202-dc95c3cce1c2.png)

**Comment by cjx82630** [comment]
30分钟后更新.
Fixed.Please manually update in 30 minutes.

**Comment by swling** [comment]
丢人现眼的玩意，不愿看广告，就别去人家网站就好了。

**Comment by swling** [comment]
原来就是你们两个一直在针对我的网站。很爽嘛，整个页面就那么一个广告，你俩摸着良性说，这个广告过分吗？
没有充足的，断人钱财，如杀人父母，你们的每一个过分举动都会记录在世间，请允许我给予你们深深的祝福！！！

**Comment by swling** [comment]
原来就是你们两个一直在针对我的网站。很爽嘛，整个页面就那么一个广告，你俩摸着良性说，这个广告过分吗？
没有充足的正当理由，断人钱财，如杀人父母，你们的每一个过分举动都会记录在世间，请允许我给予你们深深的祝福！！！

**Comment by swling** [comment]
截图备忘：
[https://wndwp.com/archives/1310](https://wndwp.com/archives/1310)
愿你们睡得安稳哦！！
